### ISSUE TITLE
Remove run.sh and build.sh

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#103]
@lasote 

Since we use `build.py` to build, test and upload our images, I think both build.sh and run.sh could be removed from this project. Docker Compose is able to do the same tasks.

**Comment by Croydon** [comment]
Aren't these files meant to build and run the containers locally more easily?

But I agree that it is a lot of boilerplate

**Comment by uilianries** [comment]
Yes, but we can use `docker-compose run` instead and put all examples on README.
