### ISSUE TITLE
images to support cross-compilation for android

### ISSUE THREAD

**Issue by CAMOBAP795** [conan-io/conan-docker-tools#104]
### Intro

Recently I pushed several PRs to fix/support https://github.com/conan-community/conan-opencv/pull/12 cross-compilation for Android

I did all test locally and then push it to review, before merge CI must be passed, for now CI covers linux & windows compilation only

### Suggestion

I would like to cover cross-compilation for Android too

### What I have tried

I have tried to run on https://github.com/dockcross/dockcross/tree/master/android-arm but it fails with [`/bin/sh: 1: cd: can't cd to project`](https://travis-ci.org/CAMOBAP795/conan-log4cplus/builds/497867759) error

Initially I thought that problem that user `conan` don't eixists in `dockcross/android-arm`, so I changed `CONAN_DOCKER_HOME` to `/root` but it doesn't help, issue remains the same

Full evn list: `ANDROID_NDK_HOME=/build/android-ndk-r16b CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=dockcross/android-arm CONAN_DOCKER_IMAGE_SKIP_UPDATE=True CONAN_DOCKER_HOME=/root CONAN_ARCHS=armv7hf CONAN_BUILD_TYPES=Debug`

I will continue debugging locally

**Comment by madebr** [comment]
I just had a similar issue and that issue was **selinux**.

`build.py` failed with the last line looking like: 
```
Exception: Error building: sudo -E docker run --rm -v "/home/maarten/programming/conan-ps2_toolchain_installer:/home/conan/project" -e CONAN_USERNAME="madebr" -e CONAN_DOCKER_IMAGE="conanio/gcc7" -e CONAN_CHANNEL="testing" -e CONAN_LOGIN_USERNAME="madebr" -e CONAN_REFERENCE="ps2_toolchain_installer/20190225@madebr/testing" -e CPT_PROFILE="@@include(default)@@@@[settings]@@arch_build=x86_64@@os_build=Linux@@[options]@@@@[env]@@@@[build_requires]@@@@" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_RETRY="3"  conanio/gcc7 /bin/sh -c " cd project &&  run_create_in_docker "
```

When I added the `:Z` option to the bind mount, it worked on my system.

So I changed the command to
```
sudo -E docker run --rm -v "/home/maarten/programming/conan-ps2_toolchain_installer:/home/conan/project:Z" -e CONAN_USERNAME="madebr" -e CONAN_DOCKER_IMAGE="conanio/gcc7" -e CONAN_CHANNEL="testing" -e CONAN_LOGIN_USERNAME="madebr" -e CONAN_REFERENCE="ps2_toolchain_installer/20190225@madebr/testing" -e CPT_PROFILE="@@include(default)@@@@[settings]@@arch_build=x86_64@@os_build=Linux@@[options]@@@@[env]@@@@[build_requires]@@@@" -e CONAN_TEMP_TEST_FOLDER="1" -e CPT_UPLOAD_RETRY="3"  conanio/gcc7 /bin/sh -c " cd project &&  run_create_in_docker "
```
