### ISSUE TITLE
Add user and password to upload packages onto the dockerized conan_server?

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan-docker-tools#118]
I'm using the conan_server from this repository for testing purposes. As far as I could see there is no user set up for uploading any packages onto it. That means a user needs to alter the server.conf manually after starting the container.
In order to support a fully automated toolchain it would be good to have a different way of setting this up. I'm not that much into docker and conan_server from the perspective of the image-creator, so there's probably already a mechanism in place that could be used?

* Is there already a way to upload packages without touching the conan_server?
* If not: What mechanism to provide this functionality would best practice?

**Comment by monsdar** [comment]
Looked again and found that there's a demo user that works:

```
conan create . demo/prerelease
conan user -r remote -p demo demo
conan upload lib/1.0.0@demo/release --all -r remote
```

Leaving this issue for visibility, closing soon.

**Comment by uilianries** [comment]
Hi @monsdar !

If you run this docker image with `-t´ you will see the conan_server folder:

    conan run --rm -t conanio/conan_server
    Using config: /root/.conan_server/server.conf
    Storage: /root/.conan_server/data
    Public URL: http://localhost:9300/v1
    PORT: 9300

You could create a custom server.conf and mount it:

    conan run --rm -t -v /custom/conan_server:/root/.conan_server conanio/conan_server

> Looked again and found that there's a demo user that works:

Thta's right, the user `demo` is the default one.

**Comment by monsdar** [comment]
I wanted to create a self-containing, temporary environment and therefore not to use volumes. Demo user was already working for me, what gave me headaches was the hostname though.

In the end I found a hack that uses `sed` to change the configuration accordingly. Here's my final version: [docker-compose.yml](https://github.com/monsdar/docker-testbed/blob/af6d8015f4efb6eb2a285ee42b4545013f32cf1f/ci_testbed/docker-compose.yml#L43) and [.gitlab-ci.yml](https://github.com/monsdar/docker-testbed/blob/af6d8015f4efb6eb2a285ee42b4545013f32cf1f/ci_testbed/project_template/hellolib/.gitlab-ci.yml#L13)
