### ISSUE TITLE
Create tag by Conan version

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#12]
Hi!

Conan 0.26 is out, but all images were created in version 0.25 (I guess). We can update conan by pip, but would be nice if the image brings the latest version ever, as lasote/conangcc63:latest. Also, would be nice to use a tag per version:

```
REPOSITORY                      TAG
lasote/conangcc63               latest
lasote/conangcc63               0.26.0
lasote/conangcc63               0.25.0
...
```
Regards.

**Comment by lasote** [comment]
Would be nice, but definitely, for that task, we would need to get ready the CI for this repository, too much for doing it manually all the time.

**Comment by uilianries** [comment]
Well, I created a PR some time ago to use Travis CI. Also, we could use GitHub webhook to start a new integration after each release.

**Comment by lasote** [comment]
Sure, I know. If I remember well it required to setup the credentials for the docker repository, I tried to move it to bintray but we had an internal discussion and it got stuck. I'll try to move it again.
