### ISSUE TITLE
Add JFrog CLI to images

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-docker-tools#122]
A fair number of Conan users I talk to are using the Docker images internally to push to Artifactory.  The Artifactory "build info" is one of the things that `conan upload` does not support, but which developers fairly regularly want to do.  With Jenkins, the Artifactory plugin helps with that.  However, for all the other CI's that do not have Artifactory plugins, the JFrog CLI is the next best way to push metadata (slightly preferable to using curl).    

On the next refactor in which you touch all the docker images, consider installing JFrog Cli.

**Comment by uilianries** [comment]
Done.

https://github.com/conan-io/conan-docker-tools/blob/050fe5ab89f188e61c3dab210339962a46f6f8e3/legacy/gcc_10/Dockerfile#L54
https://github.com/conan-io/conan-docker-tools/blob/050fe5ab89f188e61c3dab210339962a46f6f8e3/modern/base/Dockerfile#L66
