### ISSUE TITLE
Use Docker multi stage to reduce the recipe number

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#125]
### Description of Problem, Request, or Question

Months ago @SSE4 commented that we could use [Docker multistage build](https://docs.docker.com/develop/develop-images/multistage-build/) to reduce the number of recipes, but we had some limitation related to Docker Compose version supported by Travis. Since we have migrated to Azure we could re-visit this idea and try to optimize our Docker recipes.

All extra arch images, like ARM, could be merged into the default Docker recipe.

Related issue #89

**Comment by Croydon** [comment]
This looks like a good post about how we could implement that https://blog.andreiavram.ro/docker-multi-stage-builds-docker-compose/
