### ISSUE TITLE
Ubuntu 17.10 „Artful Aardvark" based containers outdated

### ISSUE THREAD

**Issue by qno** [conan-io/conan-docker-tools#131]
### Description of Problem, Request, or Question
Docker build containers based on Ubuntu 17.10 reached end of life and are not supported anymore. Installation of conan recipe dependencies fails now, because packages can't be downloaded anymore.

### Environment Details
* Conan Docker Tools image: **conanio/gccXXX**
* Conan Docker Tools image: **conanio/clangXXX**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 17.10**

### Steps to reproduce (Include if Applicable)
Build a recipe that installs dependencies with package manager, e.g. **glfw 3.3** with **conanio/gcc6**.

### Build logs (Include if Available)
[log_154_472.zip](https://github.com/conan-io/conan-docker-tools/files/3167957/log_154_472.zip)

```
Running: sudo -A apt-get update
Ign:1 http://archive.ubuntu.com/ubuntu artful InRelease
Ign:2 http://archive.ubuntu.com/ubuntu artful-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu artful-backports InRelease
Err:4 http://archive.ubuntu.com/ubuntu artful Release
  404  Not Found [IP: 91.189.88.161 80]
Err:5 http://archive.ubuntu.com/ubuntu artful-updates Release
  404  Not Found [IP: 91.189.88.161 80]
Err:6 http://archive.ubuntu.com/ubuntu artful-backports Release
  404  Not Found [IP: 91.189.88.161 80]
Ign:7 http://security.ubuntu.com/ubuntu artful-security InRelease
Err:8 http://security.ubuntu.com/ubuntu artful-security Release
  404  Not Found [IP: 91.189.91.26 80]
Reading package lists...
E: The repository 'http://archive.ubuntu.com/ubuntu artful Release' does not have a Release file.
```

**Comment by uilianries** [comment]
Hi @qno !

Please, follow the PR https://github.com/conan-io/conan-docker-tools/pull/130 to have more information about it.
