### ISSUE TITLE
Add a base image for Conan itself

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan-docker-tools#135]
It'd be very handy to have a public `conanio/conan` image (based on `python:3`) with just the Conan installation. 
Needed for separate steps for configuration, merging and deployment.

**Comment by Croydon** [comment]
But what is the real advantage over one of the existing ones?

**Comment by Minimonium** [comment]
* It's smaller
* Could be used as a Docker app
    * Could provide a local cache from the container
    * Could use mounted tools
    * Can be used to set up the mounted local cache
* Could be used as a base image for other environments aside from existing ones
* Could be used as a base image for `conan_server`

**Comment by uilianries** [comment]
After reading official Docker docs, I believe they will not accept. Not even Conda, or other popular package manager are packaged there. They only accept essential apps and services, like compilers, OS, DB manager, HTTP server, ...

Anyway, I'll write a Dockerfile based on Alpine to install only Conan. It's a valid scenario where people can use conan as service on Docker compose for enterprise CI.
