### ISSUE TITLE
pyconfig.h: No such file or directory in containers

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-docker-tools#14]
we're having some issues with Boost.Python related to python paths in the containers.  We get this error:

```
/usr/include/python2.7/pyconfig.h:7:49: fatal error: i386-linux-gnu/python2.7/pyconfig.h: No such file or directory
```
do you have any guesses as to the cause? 

I do see python-devel getting installed, and i don't see anything else fancy that might make it behave in a non-standard way.

**Comment by lasote** [comment]
Probably the 32 bits python-dev package

**Comment by solvingj** [comment]
Yes, indeed, we had to split 32 and 64 bit builds in travis into different jobs.  Thanks!
