### ISSUE TITLE
cmake variable M_LIBRARY is not set to NOTFOUND

### ISSUE THREAD

**Issue by mhofmann85** [conan-io/conan-docker-tools#140]
Hi,

I already opened an issue at: https://github.com/bincrafters/community/issues/884 . But maybe the issue is better located here.

### Description of Problem, Request, or Question
As additional information. 
I reproduced the problem with plane CMake, and in the end, CMake is not finding libM (what it is saying). The problem can be fixed, by specifying CMAKE_FIND_ROOT_PATH (see script). 
```
cmake_minimum_required (VERSION 3.9)
set(target SomeTest)
project(${target} CXX)

# the following line fixes the problem problem
set(CMAKE_FIND_ROOT_PATH /usr/arm-linux-gnueabihf/)

if(UNIX AND NOT APPLE AND NOT BEOS AND NOT HAIKU)
  find_library(M_LIBRARY m )
else()
  # libm is not needed and/or not available
  set(M_LIBRARY "")
endif()

add_library(${target} SHARED main.cpp)
target_link_libraries(${target}  ${M_LIBRARY})
```
But, I do not get it, how I get conan-docker set this environment variable correctly

I already tried to modify the profile to
```
[settings]
arch=armv7hf
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=5
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CONAN_CMAKE_FIND_ROOT_PATH=/usr/arm-linux-gnueabihf
CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
```

### Environment Details
Package Name/Version: libpng/1.6.37
Compiler+version: gcc-5.4
Docker image: conanio/gcc5-armhf
Conan version: conan 1.17.0
Python version: Python 3.7.1

### Steps to reproduce (Include if Applicable)
docker run -it -v --rm conanio/gcc5-armv7hf /bin/bash
sed -i 's/libstdc++/libstdc++11/g' ~/.conan/profiles/default
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
conan install libpng/1.6.37@bincrafters/stable --build libpng

**Comment by uilianries** [comment]
It's not a Docker image error but a package bug.

Let's continue this discussion in https://github.com/bincrafters/community/issues/884.
