### ISSUE TITLE
CentOs 6 uses old git

### ISSUE THREAD

**Issue by mjvk** [conan-io/conan-docker-tools#141]
### Description of Problem, Request, or Question
My conanfile.py uses git to get stuff. Conan calls git with the -c command line options which is not supported by the git version in centos6. 

I think a fix would be is to use a more modern git version in centos6. Unfortunately I am completely unfamiliar with docker and centos...

### Environment Details
* Conan Docker Tools image: gcc7-centos6-x86

### Steps to reproduce (Include if Applicable)
Run git with -c

### Build logs (Include if Available)
conans.errors.ConanExceptionInUserConanfileMethod: b2sum_installer/20190808@mjvk/stable: Error in source() method, line 21
	git.clone("https://github.com/BLAKE2/BLAKE2.git","master")
	CalledProcessErrorWithStderr: Command 'git -c http.sslVerify=true clone "https://github.com/BLAKE2/BLAKE2.git" . --branch master  ' returned non-zero exit status 129.
Unknown option: -c
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]

**Comment by uilianries** [comment]
Thanks for reporting, the only option we have is building a new version.
