### ISSUE TITLE
alias for clang7 image

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-docker-tools#145]
at some point, we may decide to make an additional alias for the `clang7` image, e.g. `clang70`.
/cc @uilianries @Hipony @Minimonium

**Comment by Croydon** [comment]
Is there a real docker alias function or would we need to build and upload it a second time?

**Comment by Minimonium** [comment]
You'd need to run the `docker tag`. I'm not sure how the build script should handle it in a not that hacky way though.

Example:
```
$ sudo docker tag conanio/clang7 conanio/clang70
$ sudo docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
conanio/clang7      latest              e96ae83f7f28        2 days ago          856MB
conanio/clang70     latest              e96ae83f7f28        2 days ago          856MB
```

**Comment by Croydon** [comment]
Done!
