### ISSUE TITLE
Add Clang 9

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-docker-tools#148]
Clang 9 was released 2 days ago.

  - [x] https://github.com/conan-io/conan/pull/5786
  - [x] Conan 1.19.0 released
  - [x] Ubuntu offers some official Clang 9 package: https://packages.ubuntu.com/eoan/clang-9
  - [ ] Publish Clang 9 containers

**Comment by uilianries** [comment]
Ubuntu eoan is under development, the final release will be 17/10/2019:

https://www.omgubuntu.co.uk/2019/05/ubuntu-19-10-release-features
