### ISSUE TITLE
Add Clang 7.1

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#149]
### Description of Problem, Request, or Question

LLVM have released [Clang 7.1](https://releases.llvm.org/download.html#7.1.0) but there is no Docker image available. Another important point, this version is not a regular one available on APT repo.

We have 2 options:

- Install pre-built binaries compatible with Ubuntu distro
- Build from sources

Oblivious, the first one is much easier.

**Comment by Croydon** [comment]
Did somebody actually request this? Is it needed?

**Comment by uilianries** [comment]
Nope, thinking again, it doesn't worth the effort!
