### ISSUE TITLE
gcc-9.2 support

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan-docker-tools#158]
Currently, all gcc-9 docker images support only gcc-9.1. Could you please upgrade to gcc-9.2?

**Comment by Croydon** [comment]
We are using this package: https://packages.ubuntu.com/disco/gcc-9

As soon as they have 9.2 we will pick it up soon-ish implicit

**Comment by uilianries** [comment]
As @Croydon said we use the compiler version provided by that distro to avoid any incompatibility.

**Comment by mpusz** [comment]
gcc-9.2 is a native compiler on eoan. I do not know if it will be ever updated on disco.

**Comment by uilianries** [comment]
Indeed eoan uses 9.2 by default and disco uses gcc-8 by default (but we can install gcc-9.1)

https://packages.ubuntu.com/search?keywords=gcc-9

I think we can update our Docker image since the default gcc version for eoan is gcc-9
