### ISSUE TITLE
GCC <-> GCOV version mismatch in gcc8 container

### ISSUE THREAD

**Issue by KarstenHohmeier** [conan-io/conan-docker-tools#161]
### Description of Problem, Request, or Question

Running gcov in the gcc8 container currently produces:

```
conan@0f3685a8487f:/libs/ut$ gcov ./src/main.c
./src/main.gcno:version 'A83*', prefer 'A74*'
./src/main.gcno:no functions found
```

There is a version mismatch between GCC and GCOV:

```
conan@0f3685a8487f:/libs/ut$ gcov --version
gcov (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
(...)
conan@0f3685a8487f:/libs/ut$ gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
```

Probably because GCC8 is added as an update-alternative in the Dockerfile:

```
&& update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100 \
&& update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-8 100 \
&& update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 \
&& update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-8 100 \
```

GCOV did not make the list so the binary used is still the original 7.4.0 version.
This problem may affect other images as well if they get built similarly.

### Environment Details
* Conan Docker Tools image: **conanio/gcc8:latest**
* Operating System: **Linux**
* Operation System Version: **Debian 10 Buster**

**Comment by uilianries** [comment]
Hi @KarstenHohmeier Thanks for reporting.

gcov-8 is installed as well, so we just need to set as default.

**Comment by KarstenHohmeier** [comment]
Hi @uilianries Thanks for fixing.
Yes, I pointed to gcc-8 and gcov-8 in my makefiles. That was fine as a workaround.
