### ISSUE TITLE
Ubuntu LTS update policy

### ISSUE THREAD

**Issue by tmeresinski** [conan-io/conan-docker-tools#178]
### Description of Problem, Request, or Question

I have a question, how you will react after a release of a new Ubuntu LTS version. Will you stay with Ubuntu 18.04 base image, switch to Ubuntu 20.04 base or maybe you will build both versions?

**Comment by uilianries** [comment]
We will keep 18.04.

The main problem is not about package support, but the glibc version and default compiler version.

We had many problems related to incompatible glibc version when migrating from distro version to a new one, so we prefer keeping as is.

**Comment by uilianries** [comment]
With [modern docker images](https://github.com/conan-io/conan-docker-tools/tree/master/modern) we can track LTS versions. At least, we will update when reaching EOL.
