### ISSUE TITLE
Issues with clang-9 packages on pre-19.10 Ubuntu versions

### ISSUE THREAD

**Issue by aleksa2808** [conan-io/conan-docker-tools#188]
Hi!

As mentioned in [this CCI issue](https://github.com/conan-io/conan-center-index/issues/1321) I encountered several packages from conan-center which were not working on Ubuntu 18.04 since they tried to link to stdlibc++ / glibc versions not available on this version. Since the clang-9 package is [available on 18.04](https://packages.ubuntu.com/bionic/clang-9), could the clang-9 docker image base be changed to bionic?

Thanks,
Alex

### Environment Details
* Conan Docker Tools image: **conanio/clang9**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**

**Comment by uilianries** [comment]
Since clang-9 is available for bionic and bionic is older, we can change it.

**Comment by aleksa2808** [comment]
Nice, thank you!

**Comment by Croydon** [comment]
But this would mean that every single package needs to be rebuild for Clang-9, otherwise we getting mass failures for every package which has at least one dependency, because of a too new glibc version...

**Comment by uilianries** [comment]
@Croydon you are right! So we have an impasse

**Comment by aleksa2808** [comment]
One side question: Why are there packages like nasm, zlib, libssl etc. being installed in these images? Can't they be pulled through conan?

**Comment by uilianries** [comment]
Need to be checked. They are/were pre-requisites for that environment (cmake, python, conan ...)

**Comment by uilianries** [comment]
@aleksa2808 checking again, we can't do it, because we have a lot of packages built using that docker image, as @Croydon  commented before.

About those packages, they are requirements when building (cmake, pyenv ...)

**Comment by aleksa2808** [comment]
Ok, that's understandable. 

I stopped using CCI packages directly for now because of this and issues discussed in [this issue](https://github.com/conan-io/conan/issues/3972), so on the positive side this one is not a blocker for me anymore.
