### ISSUE TITLE
incompatible ibc++.so when building with clang9 for x86 using conanio/clang9

### ISSUE THREAD

**Issue by dvd0101** [conan-io/conan-docker-tools#196]
It looks like the clang9 image only contains the libc++ library for the x86-64.

During a build (driven by ConanMultiPackager) for clang9/libc++/x86 I received:

>  /usr/bin/ld: skipping incompatible /usr/lib/llvm-9/bin/../lib/libc++.so.1 when searching for libc++.so.1
> /usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc++.so.1 when searching for libc++.so.1
> /usr/bin/ld: cannot find libc++.so.1

This build was performed on the gitlab CI so I can provide the full log if needed.

I can also reproduce the fail locally using docker and the conanio/clang9 image

### Environment Details
* Conan Docker Tools image: **conanio/clang9**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 19.10**

**Comment by uilianries** [comment]
@dvd0101 probably you a trying to build with a pre-built package which wants a different version of libc++. I recommend you building from sources in this case.

**Comment by dvd0101** [comment]
[CMakeLists.txt](https://github.com/conan-io/conan-docker-tools/files/4533058/CMakeLists.txt)
[conanfile.py.txt](https://github.com/conan-io/conan-docker-tools/files/4533059/conanfile.py.txt)

I have a minimal, reproducible example. Put the attached file in the same directory and run conan:
```
$ docker run -v $(pwd):/srv --rm -it -w /srv conanio/clang9 conan create . -s compiler.libcxx=libc++ -s arch=x86 -o test:shared=True
```

The build fails with:
```
[100%] Linking CXX shared library lib/libt.so
/usr/bin/ld: skipping incompatible /usr/lib/llvm-9/bin/../lib/libc++.so.1 when searching for libc++.so.1
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc++.so.1 when searching for libc++.so.1
/usr/bin/ld: cannot find libc++.so.1
/usr/bin/ld: skipping incompatible /usr/lib/llvm-9/bin/../lib/libc++abi.so when searching for -lc++abi
/usr/bin/ld: skipping incompatible /usr/lib/llvm-9/bin/../lib/libc++abi.a when searching for -lc++abi
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc++abi.so when searching for -lc++abi
/usr/bin/ld: cannot find -lc++abi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/t.dir/build.make:84: lib/libt.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/t.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
test/0.1.0: 
test/0.1.0: ERROR: Package 'ee98738f334458c4d685686cdc18944f53b0cc43' build failed
test/0.1.0: WARN: Build folder /home/conan/.conan/data/test/0.1.0/_/_/build/ee98738f334458c4d685686cdc18944f53b0cc43
ERROR: test/0.1.0: Error in build() method, line 37
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/home/conan/.conan/data/test/0.1.0/_/_/build/ee98738f334458c4d685686cdc18944f53b0cc43' '--' '-j8'
```

`conanio/clang9` is the last version:
```
$ docker image ls conanio/clang9
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
conanio/clang9      latest              d5708bfdac6d        3 days ago          903MB
```

**Comment by uilianries** [comment]
Hello! I recommend you using [modern](https://github.com/conan-io/conan-docker-tools/tree/master/modern) docker images, which are building compiler and their libraries from source.

For your case `conanio/clang9-ubuntu16.04`
