### ISSUE TITLE
Ninja missing in clang 10 image

### ISSUE THREAD

**Issue by kaihowl** [conan-io/conan-docker-tools#203]
### Description of Problem, Request, or Question

The current clang10 image does not install `ninja-build`. Previous incarnations of this image installed ninja. Should I switch to Makefiles as the generator and not rely on having ninja-build installed instead?

### Environment Details
* Conan Docker Tools image: **conanio/clang10:1.25.2** (sha256:b60ad3a789f1749e54ebfb182d8862de6b713ef628919a2f334b2757b88e7846)

### Steps to reproduce (Include if Applicable)
```
$ docker run -it -v $(pwd):$(pwd) -w $(pwd) conanio/clang10:1.25.2 which ninja
> returns with exit code == 1
```

**Comment by Croydon** [comment]
For recipes in the Conan Center Index we always add `ninja/1.9.0` as a build_requirement when a recipe requires it

I would recommend that you either do this too or add it as a build_requirement to your Conan profile(s)

**Comment by uilianries** [comment]
@kaihowl Ninja was installed in previous versions because we needed for projects which were in the docker images. The best way of consuming Ninja is installing it as Conan package, not from the system. Follow @Croydon's recommendation please.

**Comment by kaihowl** [comment]
Thanks, both. That makes sense and I will follow the recommendation.
