### ISSUE TITLE
Add centos 7 with gcc 9 support

### ISSUE THREAD

**Issue by rockdreamer** [conan-io/conan-docker-tools#206]
### Description of Problem, Request, or Question
I'd like to contribute an image for the above configuration

Centos6 will no longer receive maintainance updates from November 30th, 2020. Where I work we have effectively stopped supporting it. Having an updated image would help.

**Comment by dheater** [comment]
Related to #204

**Comment by uilianries** [comment]
Unfortunately we no longer keep other docker images, besides those used on Conan Center. It requires a big effort of maintenance which we can not afford right now.

For GCC9 I strongly recommend `conanio/gcc9-ubuntu16.04` which is the modern version of our images. It's based on Ubuntu 16.04, but all compilers are built from source.
