### ISSUE TITLE
Enable logs in Coanaio/conan_server docker image

### ISSUE THREAD

**Issue by deekshith-elear** [conan-io/conan-docker-tools#212]
Hi,
I'm using conanio/conan_server for storing mmy conan packages since last year. since 2 weeks I was getting 504 timeout error some time it is responding. I want to check logs of server to know what actually it is happening but conanio/conan_servevr is printing limited logs so Is there any option to enable more logs in conanio/conan_server docker container

Thanks,

**Comment by uilianries** [comment]
Hi @deekshith-elear !

I agree with @memsharded, Artifactory is the best option, I use it with Docker, so I can isolate and stop without problems. Also, you can create a volume to store its cache, I believe you are doing the same for conan-server. You take a look on the docs for further information: https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DockerInstallation 

Anyway, if you want to increase the log level and check the trace output, I recommend you:

https://docs.conan.io/en/latest/reference/env_vars.html#conan-logging-level
https://docs.conan.io/en/latest/reference/env_vars.html#conan-verbose-traceback
https://docs.conan.io/en/latest/reference/env_vars.html#conan-trace-file

Regards!

**Comment by deekshith-elear** [comment]
Thanks for the suggestion of using jfrog artifactory @uilianries @memsharded . But I didnt have much time to migrate... The wired thing I had observed is conan_server docker container is giving 504 error while doing coan install but when I was using conan download it is downloading package with out any issues. Do you have any idea on this?

**Comment by uilianries** [comment]
No idea, need more details to replicate the error.

**Comment by deekshith-elear** [comment]
Hi @uilianries, @memsharded 
Here are some logs for Conan download and Conan install. 
In conanfile.py I'm mentioning requires something like this **cococlientsdk/[~0.10.0]@jenkins/develop** 
**conan install . jenkins/develop -if=build**
DEBUG :conan_api.py   [177]: INIT: Using config '/home/venkatadeekshith/.conan/conan.conf' [2020-09-01 15:00:58,174]
DEBUG :tracer.py      [157]: CONAN_API: install(path=.,name=None,version=None,user=jenkins,channel=develop,settings=None,options=None,env=None,profile_names=None,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None),remote_name=None,verify=None,manifests=None,manifests_interactive=None,build=None,update=False,generators=None,no_imports=False,install_folder=build,lockfile=None) [2020-09-01 15:00:58,175]
DEBUG :profile_loader.py[113]: PROFILE LOAD: /home/venkatadeekshith/.conan/profiles/default [2020-09-01 15:00:58,177]
DEBUG :rest_client_common.py[156]: REST: ping: https://conan.bintray.com/v1/ping [2020-09-01 15:00:58,223]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions'] [2020-09-01 15:00:59,459]
DEBUG :rest_client_common.py[183]: REST: get: https://conan.bintray.com/v1/conans/search?q=cococlientsdk&ignorecase=False [2020-09-01 15:00:59,460]
DEBUG :rest_client_common.py[156]: REST: ping: http://conan.elear.solutions/v1/ping [2020-09-01 15:00:59,725]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'revisions', 'revisions'] [2020-09-01 15:00:59,805]
DEBUG :rest_client_common.py[183]: REST: get: http://conan.elear.solutions/v1/conans/search?q=cococlientsdk&ignorecase=False [2020-09-01 15:00:59,805]
DEBUG :rest_client_common.py[33]: REST ERROR: 500 [2020-09-01 15:01:59,874]

**conan download cococlientsdk/0.10.0@jenkins/develop -r conan_server** 
DEBUG :conan_api.py   [177]: INIT: Using config '/home/venkatadeekshith/.conan/conan.conf' [2020-09-01 15:04:58,630]
DEBUG :tracer.py      [157]: CONAN_API: download(reference=cococlientsdk/0.10.0@jenkins/develop,packages=None,remote_name=conan_server,recipe=False) [2020-09-01 15:04:58,632]
DEBUG :rest_client_common.py[156]: REST: ping: http://conan.elear.solutions/v1/ping [2020-09-01 15:04:58,637]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'revisions', 'revisions'] [2020-09-01 15:04:58,720]
DEBUG :rest_client_common.py[183]: REST: get: http://conan.elear.solutions/v1/conans/cococlientsdk/0.10.0/jenkins/develop/download_urls [2020-09-01 15:04:58,723]

**Comment by uilianries** [comment]
As you can see, the flow is different in both commands.

> DEBUG :rest_client_common.py[183]: REST: get: http://conan.elear.solutions/v1/conans /search?q=cococlientsdk&ignorecase=False [2020-09-01 15:00:59,805]
> DEBUG :rest_client_common.py[33]: REST ERROR: 500 [2020-09-01 15:01:59,874]

It took 1 minute before failing, because the default is 1 minute. As you are running conan server for a long time, probably it contains many packages. I would try increasing the timeout limit.

You can update your conan.conf file: https://docs.conan.io/en/latest/reference/config_files/conan.conf.html
