### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by raketenolli** [conan-io/conan-docker-tools#215]
### Description of Problem, Request, or Question

This error appears when running a docker image, e.g. conanio/gcc9, or building a docker image, e.g. conan-io/conan-docker-tools/gcc_9-armv8, on a Raspberry Pi 4.

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

Maybe I'm misunderstanding something and I'm not supposed to use the Docker images on an Arm "build" system. I would like to use a Docker container running on a Raspberry Pi to use as a build/debug environment for embedded devices.

### Environment Details
* Conan Docker Tools image: **e.g. conanio/gcc9**
* Hardware: **Raspberry Pi 4**
* (Build) Architecture: **aarch64**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 20.04**
* Python version (If you are building some image): **python 3.8.2**
* Docker version: **19.03.12**

### Steps to reproduce (Include if Applicable)

```
sudo docker run -it conanio/gcc9 bash
```

or

```
git clone https://github.com/conan-io/conan-docker-tools.git
cd conan-docker-tools/gcc_9-armv8
sudo docker build -t gcc9-armv8 .
```

### Build logs (Include if Available)

Hard to copy and paste, but when running a container I only get the error message, then the container stops and the system returns to the command line.

When building the image, the error appears during the `RUN` command at the end of the `Dockerfile`, but no further information is provided.

**Comment by uilianries** [comment]
We projected the ARM images for cross-building so running directly won't work, you should build from sources, just like you did. You case is more particular, but unfortunately I have no experience running docker in Rasp hardware. Probably it will require a workaround.
