### ISSUE TITLE
Add Android NDK r21

### ISSUE THREAD

**Issue by martin-schulze-vireso** [conan-io/conan-docker-tools#216]
### Description of Request

The current android-clang8 containers use NDK r19c.

Please provide an android-clang9 with the latest NDK (r21) which can create packages for consumption with modern android development pipelines.

**Comment by Croydon** [comment]
It might be better to use a android-ndk Conan package as a build_require than having too many specialized container images

Check out 

https://github.com/bincrafters/conan-android_ndk_installer
https://conan.io/center/android_ndk_installer?legacy=true

There is also an attempt to migrate the recipe to the Conan Center Index https://github.com/conan-io/conan-center-index/pull/3004

**Comment by martin-schulze-vireso** [comment]
Yes, I was not aware of this when I created this issue and the PR.
