### ISSUE TITLE
clang-10 and clang-11 no longer include ninja

### ISSUE THREAD

**Issue by foonathan** [conan-io/conan-docker-tools#232]
### Description of Request

I am using the containers for CI builds. I've noticed that clang10 and clang11 no longer seem to include ninja, unlike the previous versions. Can ninja be added back?

**Comment by Croydon** [comment]
I'm not sure if we should. The images should be as minimalist as possible in order to better control the builds. For Conan Center Index recipes we add ninja as a build_requirement() in every recipe which requires Ninja

**Comment by foonathan** [comment]
So why is ninja included in all other images I've been using?

**Comment by Croydon** [comment]
It is one thing to do things differently when adding new images for new compilers, but removing stuff from already existing images, can break people

**Comment by uilianries** [comment]
@foonathan prefer [ninja/1.10.2@](https://conan.io/center/ninja) instead. We can't control or predict the version provided from Ubuntu.

**Comment by Croydon** [comment]
I think this issue can be closed, if @foonathan has no further questions

**Comment by foonathan** [comment]
I'd still prefer if they were included by default, but if you don't want it, that's okay, and I'll continue working around it.

**Comment by Croydon** [comment]
I think the general direction is clear, we want to pre-require as less as is reasonable and we add ninja as build_requires for all recipes which need it, hence it should not be added to the containers

I think this issue can be closed

**Comment by uilianries** [comment]
Please, use https://conan.io/center/ninja
