### ISSUE TITLE
jenkins-jnlp-slave has still CentOS 6 stuff

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-docker-tools#242]
The directory `jenkins-jnlp-slave` still has some CentOS 6 stuff, which probably should be deleted to

At least the directory `centos6` and the references in the `Readme.md`

Since I'm not really familiar with the Jenkins stuff, I don't feel comfortable doing that myself

**Comment by uilianries** [comment]
As we moved to legacy folder, I don't think we need to keep more effort over legacy images
