### ISSUE TITLE
Wrong libc++ version installed with clang-11

### ISSUE THREAD

**Issue by Woazim** [conan-io/conan-docker-tools#251]
https://github.com/conan-io/conan-docker-tools/blob/9a26bad2285a4b87d0c20e6b664d64b7dbb1a95d/clang_11/Dockerfile#L39-L40

These two lines must be:
```
       libc++-11-dev \
       libc++abi-11-dev \
```
Otherwise, the installed version is to old (6 or 7, I don't remember). My proposal is consistent with llvm official [page](https://apt.llvm.org/#install_stable).

Related to https://github.com/conan-io/conan-center-index/pull/4630

**Comment by ericLemanissier** [comment]
This can now be closed
