### ISSUE TITLE
Add gcc-11 docker image

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-docker-tools#258]
### Description of Problem, Request, or Question

gcc 11.1 has been released on 2021-04-27.
It would be nice to have a docker image available with this compiler.

It looks like Ubuntu 21.04 provides a gcc-11 package:
https://packages.ubuntu.com/hirsute/gcc-11

### Environment Details
* Conan Docker Tools image: **conanio/gcc11**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Python version (If you are building some image): **python 3.7.0**

**Comment by uilianries** [comment]
Done by #260
