### ISSUE TITLE
Expanding Modern images to include base Alpine distro

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-docker-tools#269]
> Considering the rapid shift to cloud, new software being built for Alpine... does the approach you've taken carry through to other "base distros"

I'm really a big fan of Alpine and I mentioned it to @SSE4 some days ago, that we could consider building for Alpine as well. Not sure if the approach in CCI would be to cross-compile or use a new collection of docker images based in Alpine. In this repo it would make a lot of sense to provide images for Alpine using the same approach. BUT, let's finish with the Ubuntu-based ones, probably much more needed, and then we can think about Alpine. @prince-chrismc , would you mind open an issue? It is not something we can work on right now, but if someone using this same approach wants to contribute... 😃

_Originally posted by @jgsogo in https://github.com/conan-io/conan-docker-tools/issues/267#issuecomment-856773997_

**Comment by uilianries** [comment]
We can create a simple Docker image with conan client installed on Alpine.

Using Alpine as base image would be possible, but there are some considerations, like the glibc version and LTS support. We also need to install a bunch of system packages which should be available. We know they are available on Ubuntu, but need to check if they are available for Alpine.

**Comment by jgsogo** [comment]
It would be amazing if we only need to change these two lines: https://github.com/conan-io/conan-docker-tools/blob/c006112c83d9df383f709ada09e307836e4bb90b/modern/.env#L29 😄

**Comment by uilianries** [comment]
Alpine does not use apt, but apk instead: https://pkgs.alpinelinux.org/packages

Still, I think it's a valid idea. We choose Ubuntu in the past (2016) due its popularity. Now we have better options, including Alpine.

**Comment by Croydon** [comment]
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by AndreyMlashkin** [comment]
It would be great to have a more lightweight docker image rather then ubuntu

**Comment by jgsogo** [comment]
The main purpose of the images in this repository is to serve ConanCenter. As long as that requirement is satisfied I don't mind building more images using other distributions... but keeping complexity under control, we have to maintain this repository and it is on the critical path for ConanCenter.
