### ISSUE TITLE
CI failing often

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-docker-tools#29]
Don't know exactly why. Check latests travis builds.

**Comment by uilianries** [comment]
some log?

**Comment by lasote** [comment]
https://travis-ci.org/conan-io/conan-docker-tools

**Comment by uilianries** [comment]
looks like we lost some packages support from ubuntu

we could update our images to use some LTS version

**Comment by Croydon** [comment]
I had similar issues and updated our Docker containers to Ubuntu 18.04.
It is still in development but it will be the next LTS soon.

**Comment by theirix** [comment]
Huh, I found a reason after a hour of debugging containers.

```bash
docker run --rm -it lasote/conangcc6 /bin/bash
conan@f9fbdb121b34:~$ ls -l /usr/bin/gcc
lrwxrwxrwx 1 root root 21 Jan 26 16:50 /usr/bin/gcc -> /etc/alternatives/gcc
conan@f9fbdb121b34:~$ ls -la /etc/alternatives/gcc
lrwxrwxrwx 1 root root 14 Jan 26 16:50 /etc/alternatives/gcc -> /usr/bin/g++-6
```

See? gcc points to g++ :-) It breaks source code autodetection almost for all C projects.

**Comment by lasote** [comment]
Uh! Sorry for that. I'll try to update the gcc 6 container asap

**Comment by lasote** [comment]
gcc6 image uploaded, please check!

**Comment by theirix** [comment]
Fixed for two different Travis builds at least. Thanks for a quick fix!

**Comment by lasote** [comment]
Thank you for reporting

**Comment by Croydon** [comment]
This is fixed now?

**Comment by lasote** [comment]
Yes
