### ISSUE TITLE
how to deal with a library that need a glibc version superior to 2.23 on modern image

### ISSUE THREAD

**Issue by Tudyx** [conan-io/conan-docker-tools#303]
### Need a higher glibc version on modern image

For building my application i have a dependency to  **libevent** which use the  `getrandom` function of  **glibc**. Unfortunately the `getrandom` function was only [added in **glibc** 2.25](https://sourceware.org/legacy-ml/libc-alpha/2017-02/msg00079.html).

I used the modern image, which uses the latest **glibc** available version for **ubuntu 16.04**, the **glibc 2
23**.

How to you think i should deal with this problem? I think of several solutions.
- Wait for **Ubuntu 16.04** to have support for **glibc 2.25** (if it will one day)
- Install a newer version of **glibc** from other source than **apt** on the modern image
- Build my own image with a newer **Ubuntu** distro to get a more recent version **glibc**

### Environment Details
* Conan Docker Tools image: **conanio/gcc10-ubuntu16.04:1.39.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**

**Comment by jgsogo** [comment]
`libevent` is currently available in ConanCenter, also for GCC 4.9 using the old docker images. You can use `conan search libevent/2.1.12@ -r conancenter --table=output.html` and check the packages available.

GCC 4.9 uses `trusty` (v14) as base image, so I expect it to have lower version of `glibc`. I cannot see any feature disabled explicitly in our recipe (https://github.com/conan-io/conan-center-index/blob/master/recipes/libevent/all/conanfile.py), but maybe you are enabling something extra. Is it the case? Can you check what is different in your build from ours? Thanks!

---

On the other hand, we are worried about this kind of situation, so your feedback is very welcome. From ConanCenter perspective it is very important to use the same `glibc` for all the packages (it would for `stdlibc++` as well, we found it was not going to be feasible). Using the same system libraries guarantee that all binaries can work on all images, this is important for build-requires where we are removing some information from the packageID (like the compiler). Using lower version has two more advantages: it maximizes the compatibility of binaries generated, and if we need to move to something newer we can do it.

**Comment by Tudyx** [comment]
I created a minimalist project to reproduce the error and i realized that the problem didn't come form **libevent** but from **spdlog** version **1.9.2**. 
[Here](https://gitlab.com/Tudyx/test-modern-conan-image) you can find the  project i created (Just a `hello world` with **spdlog**) which reproduces the error.
More interesting for you, you can find the full error in the  [job log](https://gitlab.com/Tudyx/test-modern-conan-image/-/jobs/1603066403)

**Comment by uilianries** [comment]
@Tudyx you are using the new docker images, which are not compatible with old Docker images. I suggest you building from sources or not using new Docker images. They will become the standard in the future, and we will need to rebuild and upload all packages again, but until there, we will use the legacy images. Basically we use different Ubuntu versions according the compiler version, the GCC10 image is based on Ubuntu Focal (20.04), see [here](https://github.com/conan-io/conan-docker-tools/blob/master/gcc_10/Dockerfile#L1), but you are using a Docker image based on Ubuntu 16.04, it won't work. Thus, you have to build from sources with you want to use new Docker images, or just the current Docker image `conanio/gcc10`.

**Comment by uilianries** [comment]
> I don't understand what you mean by "building from source"? That i build the wanted version of glibc on the modern image?

Download the source files and build in the docker container.

> That i build the wanted version of glibc on the modern image?

The glibc is a very basic package, which is used for all the system, so we can not just build a new version of glibc and switch. It would break all the system.

**Comment by Zvicii** [comment]
I have run into the same issue, the reason is the prebuilt libevent you downloaded from conan requires getrandom.
so you have to force libevent to build from source.
just add `--build=libevet` to `conan install`

**Comment by uilianries** [comment]
@Zvicii thank you for sharing!

**Comment by Tudyx** [comment]
Thanks a lot @Zvicii  this work for me! Thank you also @uilianries for yours explanations
