### ISSUE TITLE
[xenial] Configure Conan inside the image

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-docker-tools#304]
I'm proposing to run one extra step after installing Conan in the new images:

```
conan config init
conan profile update settings.compiler.libcxx=libstdc++11 default
``` 

IMHO, I think that `libstdc++11` is probably a better default if you just start to use one of these images and want to build something.

**Comment by uilianries** [comment]
As it doesn't affect Conan Center, and libstdc++11 will be the default one for Conan 2.0, I agree.
