### ISSUE TITLE
Experience with building from head using the modern images

### ISSUE THREAD

**Issue by HappyCerberus** [conan-io/conan-docker-tools#305]
This is not an issue as such, I just wanted to share my experience modifying the modern images to build from Git HEAD for `clang` & `gcc`.

It went reasonably smoothly, with two main observations:

- `gcc` requires the `flex` package to build from HEAD
- `clang` requires at least `clang11` to build from HEAD (missing library header otherwise), it might be worthwhile to have a bootstrap clang version as a variable

The commit on my fork is here: https://github.com/HappyCerberus/conan-docker-tools/commit/845caab1db411907665802ec8089a6467c0db427

Thanks for making these images, it made things a lot easier for me.

**Comment by uilianries** [comment]
@HappyCerberus Thank you for sharing! Indeed we will need to update those Docker images and your points are relevant. Good to know about clang 11, indeed Clang change some things from release to release, that's why we need to drop older versions.
