### ISSUE TITLE
Docker Images for x86

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#31]
Hi!

As we know, all images support both x86 and x86_64 builds. However, when we need to install some system package that is not a Conan package yet or is very distro dependent, we need to run SystemPackageTools.

Unfortunately, many packages are not prepared to be installed on same system using arch variation. For example, when I need to install some amd64 deb package on Ubuntu, the same header directories are used by i386 version. As result, we have a conflict during install. 

As workaround, we append the target on package name, please check our [SDL2](https://github.com/bincrafters/conan-sdl2/blob/stable/2.0.7/conanfile.py#L61) recipe to understand better. This works well when we have only one arch build by job.

Would be nice to provide recipes without this workaround, including their package. But, to have such situation, we need to create new Docker images, based on 32-bits arch. Fortunately, we have official docker images for Ubuntu 32-bits on [hub.docker](https://hub.docker.com/r/i386/ubuntu/)

My suggestion to solve such problem, is implement 32 bits version of Conan docker images. I know that this will increase (duplicate) the number of images, but will provide a way to build our recipes with no workarounds to solve multi-arch limitations. As done before, I could help to implement such images.

Regards!

/cc @solvingj

**Comment by lasote** [comment]
Sure, support images for 32 bits and in general any combination that can help to develop, generate or test packages is always welcome. Your help as always, very appreciated.

**Comment by uilianries** [comment]
Thanks! I'll start this task soon.

**Comment by solvingj** [comment]
awesome work!!
