### ISSUE TITLE
Update docker images

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#32]
Hi!

@solvingj reported about an error during [Boost Python build](https://travis-ci.org/bincrafters/conan-boost_python/jobs/335001227#L1954). As you can see, we have distribution support error.

After that, I read [Ubuntu EOF page](https://www.ubuntu.com/info/release-end-of-life). Well, zesty (17.04) is dead.

We need to update all images to prevent EOF. IMO, would be nice to use Ubuntu 18.04 as base.

Regards!

**Comment by solvingj** [comment]
This may also be affecting SDL2 and zmq packages now.

**Comment by solvingj** [comment]
This is good, because it is already starting to hold up boost because it's causing `boost_python` to fail,

**Comment by uilianries** [comment]
Fixed by #33
