### ISSUE TITLE
[Question] How to run a docker container(with jnlp-slave) connect to our private Jenkins server?

### ISSUE THREAD

**Issue by nmgwddj** [conan-io/conan-docker-tools#345]
I have already build a docker image with jnlp-slave: 
```
docker build . -t conanio/jnlp-slave-gcc7-armv8 --build-arg SOURCE_CONANIO_IMAGE=conanio/gcc7-armv8 --build-arg CONAN_VERSION=1.43.0
```
How to run it and connect to our private Jenkins server?

**Comment by uilianries** [comment]
Hello, your question is related how to configure Jenkins, not to Conan docker images themself. 

What I can do is pointing some tutorials where people show how to configure Jenkins with a docker container as slave:

- https://devopscube.com/jenkins-master-build-slaves-docker-container/ or any tutorial related. 
- https://www.bogotobogo.com/DevOps/Docker/Docker-Jenkins-Master-Slave-Agent-ssh.php
- https://kamrul.dev/setup-jenkins-in-different-servers-as-master-slave-within-docker/

Regards!

**Comment by nmgwddj** [comment]
Thank you so much.
