### ISSUE TITLE
[suggestion] Obtain IronBank accreditation for conanio docker images

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan-docker-tools#349]
### Description of Request

I'm proposing that the images provided in conan-docker-tools are hardened such that they can be accredited for inclusion in the [U.S. Department of Defense's Iron Bank](https://repo1.dso.mil/dsop?page=1). My understanding of what's required to achieve this is essentially hardening the conanio images by following the [DevSecOps Enterprise Container Hardening Guide](https://dl.dod.cyber.mil/wp-content/uploads/devsecops/pdf/Final_DevSecOps_Enterprise_Container_Hardening_Guide_1.1.pdf).

The benefit of this is that it would further facilitate a robust security posture to mitigate supply chain attacks, such as those that have recently occurred in both [PyPI](https://arstechnica.com/information-technology/2021/11/malware-downloaded-from-pypi-41000-times-was-surprisingly-stealthy/) and [npm](https://arstechnica.com/information-technology/2021/12/malicious-packages-sneaked-into-npm-repository-stole-discord-tokens/). Hardening these docker images will make it easier for enterprise organizations in both the public and private sector to trust the binaries provided on CCI and the usage of the existing tools provided in conan-docker-tools.

### Context

I noticed recently that JFrog announced the completion of an accreditation process for Artifactory to be included in the Ironbank [[1](https://jfrog.com/blog/a-peek-at-jfrogs-iron-bank-accreditation-for-xray-and-artifactory/)][[2](https://jfrog.com/blog/jfrog-ironbank-certification/)][[3](https://repo1.dso.mil/dsop/jfrog/artifactory/artifactory)]. It would be good for the entire suite of JFrog C++ tools to have that same accreditation.

More resources: 
* https://public.cyber.mil/devsecops/
* https://software.af.mil/dsop/services/

**Comment by uilianries** [comment]
It sounds interesting, it will give credibility and reliability to CDT. 

What we need to do? Is there a guideline?

**Comment by samuel-emrys** [comment]
> What we need to do? Is there a guideline?

Yeah, you can follow the [DevSecOps Enterprise Container Hardening Guide](https://dl.dod.cyber.mil/wp-content/uploads/devsecops/pdf/Final_DevSecOps_Enterprise_Container_Hardening_Guide_1.1.pdf). There is also a [contributor onboarding](https://repo1.dso.mil/dsop/dccscr/-/tree/master) document on one of their gitlab repos. To pull the high level requirements out of the contributor guide:

> Containers must follow a rigorous set of processes and requirements in order to receive an approval. Technical requirements and details can be found in this Contributor Onboarding Guide. However, at a high level, applications must follow the following requirements:
> * [Rebasing the container onto an approved base image (Red Hat UBI, distroless, etc)](https://repo1.dso.mil/dsop/dccscr/-/blob/master/Hardening/Dockerfile_Requirements.md#requirements)
> * Internet disconnected build processes
> * The application and all containers must be supported by a vendor, open source community, or government entity
> * You must be working with the latest of the release series for your dependencies and application
> * Timely justifications of all findings from the following scanners:
>     * OpenSCAP: DISA STIG compliance
>     * Twistlock: CVE identification
>     * Anchore: CVE and DoD compliance identification
> * Continuous monitoring (currently every 12 hours) and timely submission of justifications for any new findings
> * Submission of any new application update(s) no later than the day of public release

So it looks like the big change that would be required is moving the base image to one they've already hardened - the suggested ones appear to be RHEL7 and RHEL8. I realise that this is probably a big ask given the recent move to select ubuntu 16.04 for glib compatability - might the same thing be achieved with RHEL?

**Comment by samuel-emrys** [comment]
A little bit more research indicates that RHEL UBI8 has [glibc 2.28](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.0_release_notes/rhel-8_0_0_release#compilers_and_development_tools_3), whilst RHEL UBI7 has [glibc 2.17](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.0_release_notes/sect-red_hat_enterprise_linux-7.0_release_notes-compiler_and_tools-glibc). It also looks like they [aim for an immediate update of the universal base image as released by RedHat](https://repo1.dso.mil/dsop/redhat/ubi/ubi8), however it seems like the glibc version remains constant for the major versions

**Comment by jgsogo** [comment]
Hi! Sorry for answering too late.

The main purpose of the docker images we are building from this repository is to serve the needs of the CI behind ConanCenter, of course, we are glad to provide this work freely available for the community and we try to match our needs with the feedback coming from outside users.

We've asked internally in JFrog about this topic and we've found another team working on this kind of accreditation for Artifactory. They have told us that it requires a huge amount of work. Even if we can work together and take advantage of their learnings, the scope of the docker images we are generating here is not comparable to the ones in the Artifactory context, and the purpose they serve is very different... also the resources that the company can dedicate to them.

I'm sorry to say this is an effort we cannot commit to.

**Comment by samuel-emrys** [comment]
> Hi! Sorry for answering too late.
> 
> The main purpose of the docker images we are building from this repository is to serve the needs of the CI behind ConanCenter, of course, we are glad to provide this work freely available for the community and we try to match our needs with the feedback coming from outside users.
> 
> We've asked internally in JFrog about this topic and we've found another team working on this kind of accreditation for Artifactory. They have told us that it requires a huge amount of work. Even if we can work together and take advantage of their learnings, the scope of the docker images we are generating here is not comparable to the ones in the Artifactory context, and the purpose they serve is very different... also the resources that the company can dedicate to them.
> 
> I'm sorry to say this is an effort we cannot commit to.


Given that this is essentially just populating a container with a compiler, I didn't think the amount of effort would be anything close to Artifactory, but thanks for looking into it anyway :)
