### ISSUE TITLE
[rfc] Upgrade Git version

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-docker-tools#357]
I´ve been using some of the new images with Github actions, and realized they use quite old Git version `2.8` (the one for Ubuntu 16.04 in new images). Some actions (`actions/checkout@v2`) requires newer Git version.

I think nothing is stopping us from using _latest_ Git in all our docker images. There is no restriction on Conan client-side AFAIK.

**Comment by uilianries** [comment]
Two options, take a look on external package repositories, or build from sources. The second option we already do for old and deprecated Docker images.

**Comment by jgsogo** [comment]
This is what I do before those actions:

```
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt-get update
sudo apt-get install git -y
```
