### ISSUE TITLE
build break while cross compiling for opencv dependencies in docker: conanio/gcc7-armv7

### ISSUE THREAD

**Issue by qiao-tw** [conan-io/conan-docker-tools#368]
### Environment Details
* Conan Docker Tools image: **conanio/gcc7-armv7:1.44.1**
* Operating System: **macOS**
* Operation System Version: **macOS 12.1**
* Python version (If you are building some image): **python 3.7.5**

### Steps to reproduce (Include if Applicable)
1. in the project root folder, enter docker environment with the following command:
```docker run -it  -v$(pwd):/home/conan/project --rm conanio/gcc7-armv7 /bin/bash```
2. install ```libgtk2.0-dev``` with the following command:
```sudo apt update; sudo apt install libgtk2.0-dev```
3. in the project root folder, create a conanfile.txt will the following content:
```
[requires]
opencv/4.5.3

[generators]
cmake

[options]
opencv:with_ffmpeg=False
opencv:dnn=False
```
2. in the project root folder, run
``` mkdir build; cd build; conan install .. --build=missing```
### Build logs (Include if Available)
conan@d5f115e81442:~/project/build$ conan install .. --build=missing
Configuration:
[settings]
arch=armv7
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

WARN: libtiff/4.3.0: requirement libwebp/1.2.2 overridden by opencv/4.5.3 to libwebp/1.2.1
jbig/20160605: Not found in local cache, looking in remotes...
jbig/20160605: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.33k]
Downloading conanfile.py completed [2.58k]
Downloading conan_export.tgz completed [0.35k]
Decompressing conan_export.tgz completed [0.00k]
jbig/20160605: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    ade/0.1.1f from 'conancenter' - Cache
    eigen/3.3.9 from 'conancenter' - Cache
    gtk/system from 'conancenter' - Cache
    jasper/2.0.33 from 'conancenter' - Cache
    jbig/20160605 from 'conancenter' - Downloaded
    libdeflate/1.9 from 'conancenter' - Cache
    libjpeg/9d from 'conancenter' - Cache
    libpng/1.6.37 from 'conancenter' - Cache
    libtiff/4.3.0 from 'conancenter' - Cache
    libwebp/1.2.1 from 'conancenter' - Cache
    opencv/4.5.3 from 'conancenter' - Cache
    openexr/2.5.7 from 'conancenter' - Cache
    quirc/1.1 from 'conancenter' - Cache
    xz_utils/5.2.5 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
    zstd/1.5.2 from 'conancenter' - Cache
Packages
    ade/0.1.1f:0b9da21d52bd90e64a7c7c66777230d5767d297c - Cache
    eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    gtk/system:cc5e5ca8b619d2dffaaeae1e4924ae3ce085a8f1 - Cache
    jasper/2.0.33:3c15e011e1256608a208818bb403dd13a740db29 - Build
    jbig/20160605:99c019715e3b6f4e40e125add30e7d474d0f55fe - Build
    libdeflate/1.9:15eab756bd1cec551ba6321ea0f516c3af2dc7f2 - Build
    libjpeg/9d:15eab756bd1cec551ba6321ea0f516c3af2dc7f2 - Build
    libpng/1.6.37:f40b1d339af2b43b1483874b83cbf96baddaea9c - Build
    libtiff/4.3.0:5ca92098cd45af853421c20dbb0e61cea652152d - Build
    libwebp/1.2.1:959c9afe4579376fb30bc333ca59d3666423daff - Build
    opencv/4.5.3:2a1cfaaf625587becb67674324c0e3f19ccccaa3 - Build
    openexr/2.5.7:1fe3a8818dcb37d67a3043841c95b194167e3825 - Build
    quirc/1.1:c2ec51df91c8a415e244646e1c77820bef2abfaf - Build
    xz_utils/5.2.5:15eab756bd1cec551ba6321ea0f516c3af2dc7f2 - Build
    zlib/1.2.11:15eab756bd1cec551ba6321ea0f516c3af2dc7f2 - Build
    zstd/1.5.2:15eab756bd1cec551ba6321ea0f516c3af2dc7f2 - Build

Cross-build from 'Linux:x86_64' to 'Linux:armv7'
Installing (downloading, building) binaries...
ade/0.1.1f: Already installed!
eigen/3.3.9: Already installed!
gtk/system: Already installed!
Downloading conan_sources.tgz completed [1.16k]
Decompressing conan_sources.tgz completed [0.00k]
jbig/20160605: Configuring sources in /home/conan/.conan/data/jbig/20160605/_/_/source
Downloading 5d8f5f6fa71766ced5e828bf7bfff642ddb8a6ad.zip:   0%|          | 0.00/412k [00:00<?, ?BDownloading 5d8f5f6fa71766ced5e828bf7bfff642ddb8a6ad.zip:  24%|##4       | 100k/412k [00:00<00:01Downloading 5d8f5f6fa71766ced5e828bf7bfff642ddb8a6ad.zip:  73%|#######2  | 300k/412k [00:00<00:00                                                                                                 Downloading 5d8f5f6fa71766ced5e828bf7bfff642ddb8a6ad.zip completed [412.03k]
ERROR: jbig/20160605: Error in source() method, line 55
	destination=self._source_subfolder, strip_root=True)
	ConanException: sha256 signature failed for '5d8f5f6fa71766ced5e828bf7bfff642ddb8a6ad.zip' file.
 Provided signature: 2669b49ee000150af7709b21c7656f1f6cbea09fd33116c40b41310adeb2b73e
 Computed signature: d77e120714c8a392ece060d810a77045f707787bd4790aef5ad11cc821eac147

**Comment by uilianries** [comment]
Closing this one as we are no longer maintaining ARM images.

Some considerations:
- libgtk is already available as Conan package: https://conan.io/center/gtk
- Consider dual profile when cross-building: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer
- In case of failing to build an official package, please, open an issue to https://github.com/conan-io/conan-center-index/issues/
