### ISSUE TITLE
libtiff/4.3.0 cross compile failed with docker image conanio/gcc5-armv7

### ISSUE THREAD

**Issue by qiao-tw** [conan-io/conan-docker-tools#369]
### Description of Problem, Request, or Question
As title.

### Environment Details
* Conan Docker Tools image: **conanio/gcc5-armv7:1.44.1**
* Operating System: **macOS**
* Operation System Version: **macOS 12.1**
* Python version (If you are building some image): **python 3.7.5**

### Steps to reproduce (Include if Applicable)
1. in the project root folder, run ```docker run -it  -v$(pwd):/home/conan/project --rm conanio/gcc5-armv7 /bin/bash``` to enter docker environment
2. in the project root folder, create a ```conanfile.txt``` with the following content:
```
[requires]
libtiff/4.3.0

[generators]
cmake

[options]
```

3. in project root folder, run
```mkdir build; cd build; conan install .. --build=missing```

### Build logs (Include if Available)
conan@a3ab76d455d2:~/project/build$ conan install .. --build=missing
Configuration:
[settings]
arch=armv7
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=5
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

libtiff/4.3.0: WARN: Package binary is corrupted, removing: 5bc79924dba94c5a938c43d12f7b28f61f99d0c3
conanfile.txt: Installing package
Requirements
    jbig/20160605 from 'conancenter' - Cache
    libdeflate/1.9 from 'conancenter' - Cache
    libjpeg/9d from 'conancenter' - Cache
    libtiff/4.3.0 from 'conancenter' - Cache
    libwebp/1.2.2 from 'conancenter' - Cache
    xz_utils/5.2.5 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
    zstd/1.5.2 from 'conancenter' - Cache
Packages
    jbig/20160605:d3c0ac0d1f2faa7ec4254e0767c3843fc2c34b49 - Cache
    libdeflate/1.9:fa1b6af16f2877ef8d5c9db73c164d1092e45520 - Cache
    libjpeg/9d:fa1b6af16f2877ef8d5c9db73c164d1092e45520 - Cache
    libtiff/4.3.0:5bc79924dba94c5a938c43d12f7b28f61f99d0c3 - Build
    libwebp/1.2.2:eb0b333acc2ecc782997b5e9a2b3126d184ff931 - Cache
    xz_utils/5.2.5:fa1b6af16f2877ef8d5c9db73c164d1092e45520 - Cache
    zlib/1.2.11:fa1b6af16f2877ef8d5c9db73c164d1092e45520 - Cache
    zstd/1.5.2:fa1b6af16f2877ef8d5c9db73c164d1092e45520 - Cache

Cross-build from 'Linux:x86_64' to 'Linux:armv7'
Installing (downloading, building) binaries...
jbig/20160605: Already installed!
jbig/20160605: Appending PATH environment variable: /home/conan/.conan/data/jbig/20160605/_/_/package/d3c0ac0d1f2faa7ec4254e0767c3843fc2c34b49/bin
libdeflate/1.9: Already installed!
libjpeg/9d: Already installed!
libwebp/1.2.2: Already installed!
xz_utils/5.2.5: Already installed!
zlib/1.2.11: Already installed!
zstd/1.5.2: Already installed!
libtiff/4.3.0: WARN: Build folder is dirty, removing it: /home/conan/.conan/data/libtiff/4.3.0/_/_/build/5bc79924dba94c5a938c43d12f7b28f61f99d0c3
libtiff/4.3.0: Copying sources to build folder
libtiff/4.3.0: Building your package in /home/conan/.conan/data/libtiff/4.3.0/_/_/build/5bc79924dba94c5a938c43d12f7b28f61f99d0c3
libtiff/4.3.0: Generator cmake created conanbuildinfo.cmake
libtiff/4.3.0: Generator cmake_find_package created FindZLIB.cmake
libtiff/4.3.0: Generator cmake_find_package created Findlibdeflate.cmake
libtiff/4.3.0: Generator cmake_find_package created FindLibLZMA.cmake
libtiff/4.3.0: Generator cmake_find_package created FindJPEG.cmake
libtiff/4.3.0: Generator cmake_find_package created Findjbig.cmake
libtiff/4.3.0: Generator cmake_find_package created Findzstd.cmake
libtiff/4.3.0: Generator cmake_find_package created FindWebP.cmake
libtiff/4.3.0: Aggregating env generators
libtiff/4.3.0: Calling build()
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/arm-linux-gnueabi-gcc-5 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabi-g++-5 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting language standard
-- Conan: Adjusting fPIC flag (ON)
-- Conan: Compiler GCC>=5, checking major version 5
-- Conan: Checking correct version: 5
-- Conan: C++ stdlib: libstdc++
-- Building tiff version 4.3.0
-- libtiff library version 5.7.0
-- libtiff build date: 20220201
-- Performing Test C_FLAG_Wall
-- Performing Test C_FLAG_Wall - Success
-- Performing Test C_FLAG_Winline
-- Performing Test C_FLAG_Winline - Success
-- Performing Test C_FLAG_Wformat_security
-- Performing Test C_FLAG_Wformat_security - Success
-- Performing Test C_FLAG_Wpointer_arith
-- Performing Test C_FLAG_Wpointer_arith - Success
-- Performing Test C_FLAG_Wdisabled_optimization
-- Performing Test C_FLAG_Wdisabled_optimization - Success
-- Performing Test C_FLAG_Wno_unknown_pragmas
-- Performing Test C_FLAG_Wno_unknown_pragmas - Success
-- Performing Test C_FLAG_fstrict_aliasing
-- Performing Test C_FLAG_fstrict_aliasing - Success
-- Performing Test HAVE_LD_VERSION_SCRIPT
-- Performing Test HAVE_LD_VERSION_SCRIPT - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for assert.h
-- Looking for assert.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for io.h
-- Looking for io.h - not found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for getopt
-- Looking for getopt - found
-- Looking for optarg
-- Looking for optarg - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for setmode
-- Looking for setmode - not found
-- Check size of size_t
-- Check size of size_t - done
-- Conan: Using autogenerated FindZLIB.cmake
-- Found ZLIB: 1.2.11 (found version "1.2.11")
-- Library z found /home/conan/.conan/data/zlib/1.2.11/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libz.a
-- Found: /home/conan/.conan/data/zlib/1.2.11/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libz.a
-- Found Deflate: /home/conan/.conan/data/libdeflate/1.9/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libdeflate.a
-- Conan: Using autogenerated FindJPEG.cmake
-- Found JPEG: 9d (found version "9d")
-- Library jpeg found /home/conan/.conan/data/libjpeg/9d/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libjpeg.a
-- Found: /home/conan/.conan/data/libjpeg/9d/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libjpeg.a
-- Conan: Using autogenerated Findjbig.cmake
-- Found jbig: 20160605 (found version "20160605")
-- Library jbig found /home/conan/.conan/data/jbig/20160605/_/_/package/d3c0ac0d1f2faa7ec4254e0767c3843fc2c34b49/lib/libjbig.a
-- Found: /home/conan/.conan/data/jbig/20160605/_/_/package/d3c0ac0d1f2faa7ec4254e0767c3843fc2c34b49/lib/libjbig.a
-- Found JBIG: /home/conan/.conan/data/jbig/20160605/_/_/package/d3c0ac0d1f2faa7ec4254e0767c3843fc2c34b49/lib/libjbig.a (found version "1.6")
-- Looking for jbg_newlen
-- Looking for jbg_newlen - found
-- Could NOT find LERC (missing: LERC_LIBRARY LERC_INCLUDE_DIR)
-- Conan: Using autogenerated FindLibLZMA.cmake
-- Found LibLZMA: 5.2.5 (found version "5.2.5")
-- Library lzma found /home/conan/.conan/data/xz_utils/5.2.5/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/liblzma.a
-- Found: /home/conan/.conan/data/xz_utils/5.2.5/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/liblzma.a
-- Conan: Using autogenerated Findzstd.cmake
-- Found zstd: 1.5.2 (found version "1.5.2")
-- Library zstd found /home/conan/.conan/data/zstd/1.5.2/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libzstd.a
-- Found: /home/conan/.conan/data/zstd/1.5.2/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libzstd.a
-- Library zstd found /home/conan/.conan/data/zstd/1.5.2/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libzstd.a
-- Found: /home/conan/.conan/data/zstd/1.5.2/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libzstd.a
-- Found ZSTD: /home/conan/.conan/data/zstd/1.5.2/_/_/package/fa1b6af16f2877ef8d5c9db73c164d1092e45520/lib/libzstd.a (found version "1.5.2")
-- Looking for ZSTD_decompressStream
-- Looking for ZSTD_decompressStream - found
-- Conan: Using autogenerated FindWebP.cmake
-- Found WebP: 1.2.2 (found version "1.2.2")
-- Library webpdecoder found /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpdecoder.a
-- Found: /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpdecoder.a
-- Library webpdemux found /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpdemux.a
-- Found: /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpdemux.a
-- Library webpmux found /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpmux.a
-- Found: /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpmux.a
-- Library webp found /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebp.a
-- Found: /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebp.a
-- Library webp found /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebp.a
-- Found: /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebp.a
-- Library webpmux found /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpmux.a
-- Found: /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpmux.a
-- Library webpdemux found /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpdemux.a
-- Found: /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpdemux.a
-- Library webpdecoder found /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpdecoder.a
-- Found: /home/conan/.conan/data/libwebp/1.2.2/_/_/package/eb0b333acc2ecc782997b5e9a2b3126d184ff931/lib/libwebpdecoder.a
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_INCLUDE_DIR OpenGL)
-- Could NOT find GLUT (missing: GLUT_glut_LIBRARY GLUT_INCLUDE_DIR)
-- Looking for GL/gl.h
-- Looking for GL/gl.h - not found
-- Looking for GL/glu.h
-- Looking for GL/glu.h - not found
-- Looking for GL/glut.h
-- Looking for GL/glut.h - not found
-- Looking for GLUT/glut.h
-- Looking for GLUT/glut.h - not found
-- Looking for OpenGL/gl.h
-- Looking for OpenGL/gl.h - not found
-- Looking for OpenGL/glu.h
-- Looking for OpenGL/glu.h - not found
-- Looking for pow
-- Looking for pow - not found
-- Looking for pow
-- Looking for pow - not found
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find CMath (missing: CMath_pow)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  source_subfolder/cmake/FindCMath.cmake:51 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  source_subfolder/CMakeLists.txt:131 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/conan/.conan/data/libtiff/4.3.0/_/_/build/5bc79924dba94c5a938c43d12f7b28f61f99d0c3/build_subfolder/CMakeFiles/CMakeOutput.log".
See also "/home/conan/.conan/data/libtiff/4.3.0/_/_/build/5bc79924dba94c5a938c43d12f7b28f61f99d0c3/build_subfolder/CMakeFiles/CMakeError.log".
libtiff/4.3.0:
libtiff/4.3.0: ERROR: Package '5bc79924dba94c5a938c43d12f7b28f61f99d0c3' build failed
libtiff/4.3.0: WARN: Build folder /home/conan/.conan/data/libtiff/4.3.0/_/_/build/5bc79924dba94c5a938c43d12f7b28f61f99d0c3
ERROR: libtiff/4.3.0: Error in build() method, line 183
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 178
	self._cmake.configure(build_folder=self._build_subfolder)
	ConanException: Error 1 while executing cd '/home/conan/.conan/data/libtiff/4.3.0/_/_/build/5bc79924dba94c5a938c43d12f7b28f61f99d0c3/build_subfolder' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_SYSTEM_NAME="Linux" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="5" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/home/conan/.conan/data/libtiff/4.3.0/_/_/package/5bc79924dba94c5a938c43d12f7b28f61f99d0c3" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_MODULE_PATH="/home/conan/.conan/data/libtiff/4.3.0/_/_/build/5bc79924dba94c5a938c43d12f7b28f61f99d0c3" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -Dlzma="True" -Djpeg="True" -Djbig="True" -Dzlib="True" -Dlibdeflate="True" -Dzstd="True" -Dwebp="True" -Dcxx="True" -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE="BOTH" -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY="BOTH" -Wno-dev '/home/conan/.conan/data/libtiff/4.3.0/_/_/build/5bc79924dba94c5a938c43d12f7b28f61f99d0c3'

**Comment by uilianries** [comment]
Thank you for your report, but unfortunately cross building Docker images are deprecated: https://github.com/conan-io/conan-docker-tools#gcc

However, if you find a solution and want to open an PR with a fix, it will be welcome. Regards.
