### ISSUE TITLE
clang1x -  'threads.h' file not found 

### ISSUE THREAD

**Issue by barower** [conan-io/conan-docker-tools#374]
### Description of Problem, Request, or Question
It's impossible to build C projects using `threads.h` with clang images greater than 9

### Environment Details
* Conan Docker Tools image: **conanio/clang10**, **conanio/clang10-ubuntu16.04**, **conanio/clang11**, **conanio/clang11-ubuntu16.04**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 20.04.3 LTS**
* Python version (If you are building some image):

### Steps to reproduce (Include if Applicable)
I've created very simple example project which should showcase the problem.
https://github.com/barower/conan-clang1x-threads-example
`./build_clang9.sh` - builds
`./build_clang10.sh` and `./build_clang11.sh` - won't

### Build logs (Include if Available)

Example for clang10 image:

./build_clang10.sh
Auto detecting your dev setup to initialize the default profile (/home/conan/.conan/profiles/default)
CC and CXX: clang, clang++ 
Found clang 10.0
clang>=8, using the major as version
Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=clang
	compiler.version=10
	compiler.libcxx=libstdc++
	build_type=Release
*** You can change them in /home/conan/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***

WARN: Remotes registry file missing, creating default one in /home/conan/.conan/remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (clang1x-threads-test/0.0.1): Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py (clang1x-threads-test/0.0.1): Generator txt created conanbuildinfo.txt
conanfile.py (clang1x-threads-test/0.0.1): Generator cmake created conanbuildinfo.cmake
conanfile.py (clang1x-threads-test/0.0.1): Aggregating env generators
conanfile.py (clang1x-threads-test/0.0.1): Generated conaninfo.txt
conanfile.py (clang1x-threads-test/0.0.1): Generated graphinfo
Using lockfile: '/home/project/build/conan.lock'
Using cached profile from lockfile
conanfile.py (clang1x-threads-test/0.0.1): Calling build()
-- The C compiler identification is Clang 10.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: called by CMake conan helper
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Adjusting fPIC flag (ON)
-- This project seems to be plain C, using 'Clang' compiler
-- Conan: Compiler Clang>=8, checking major version 10
-- Conan: Checking correct version: 10
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR

-- Build files have been written to: /home/project/build
Scanning dependencies of target clang1x-threads-test
[ 50%] Building C object CMakeFiles/clang1x-threads-test.dir/clang1x-threads-test.c.o
/home/project/src/clang1x-threads-test.c:1:10: fatal error: 'threads.h' file not found
#include <threads.h>
         ^~~~~~~~~~~
1 error generated.
CMakeFiles/clang1x-threads-test.dir/build.make:81: recipe for target 'CMakeFiles/clang1x-threads-test.dir/clang1x-threads-test.c.o' failed
make[2]: *** [CMakeFiles/clang1x-threads-test.dir/clang1x-threads-test.c.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/clang1x-threads-test.dir/all' failed
make[1]: *** [CMakeFiles/clang1x-threads-test.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: conanfile.py (clang1x-threads-test/0.0.1): Error in build() method, line 29
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/home/project/build' '--' '-j4'

**Comment by barower** [comment]
As noted [here](https://github.com/compiler-explorer/compiler-explorer/issues/2151#issuecomment-678833469), it looks like the proper solution is to upgrade Ubuntu to newer version in `Dockerfile`s

**Comment by uilianries** [comment]
@barower Thank you for reporting. Updating Ubuntu version is impossible due glibc and other important library versions, if we do it, all packages will break in Conan Center. I'll check an alternative solution.

**Comment by uilianries** [comment]
I checked your issue and indeed is a complicated case. I'll need to discuss with Conan team about.

We have few options here, update the glibc version, but it will cost rebuilding all packages in Conan Center and breaking all users.
Unfortunately I didn't find a stub or something which could bring threads support as a separated package.

**Comment by uilianries** [comment]
After talking to Conan team, we decided to not fix now, but only in the future (months). Changing a base Ubuntu image will cause a big problem, breaking all packages.

I suggest you updating you docker image locally as possible workaround.

**Comment by uilianries** [comment]
Thank you for your feedback!
