### ISSUE TITLE
[ci] Ability to mark some versions as _invalid_

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-docker-tools#376]
After https://github.com/conan-io/conan/issues/10611, there will be some old versions of Conan that are invalid, which won't work. We need to maintain a list of these versions so they are not built.

Around these lines, we need to skip them https://github.com/conan-io/conan-docker-tools/blob/50bf20140767f7465d972aa738107f2a1907dfb6/.ci/conan_center_index.jenkinsfile#L74

**This will be required for the CI to succeed**

**Comment by SSE4** [comment]
that's very unfortunate old releases can no longer be run...
if I need to revert to an old version, e.g. to compare the behavior or do `git bisect` to find out where the bug first appeared, I can no longer do it :(
what's the best practice to do a python release that will work exactly the same forever? (at least in the same environment, like the same ubuntu with the same bintuils/glibc/etc that was available at the release date)

**Comment by jgsogo** [comment]
There is a `pip freeze` command to dump all the versions of all the packages. Some teams use it to lock all the versions at the time of release, at least to say _"it has been tested and work with these versions"_.  

For this docker images, you can always enter the image, run that command and install exactly the same version of all the libraries in you environment, so you can reproduce the docker build if that's what you need.

**Comment by SSE4** [comment]
> For this docker images, you can always enter the image, run that command and install exactly the same version of all the libraries in you environment, so you can reproduce the docker build if that's what you need.

how exactly can I do that? e.g. if I try to build locally image for conan < 1.43, it will result in a broken conan and non-reproducible image.

**Comment by jgsogo** [comment]
You should use the image that is already built. That's the one you are trying to reproduce. It's not just about that Python library, but every other system package.

**Comment by jgsogo** [comment]
Anyway, if you already have the docker image and it runs, I see no point on building it again (if the purpose is not to debug the build process) 🤷

**Comment by SSE4** [comment]
> You should use the image that is already built. That's the one you are trying to reproduce. It's not just about that Python library, but every other system package.

I can reproduce with existing (already uploaded image). as soon as I want to rebuild it, even with some unrelated changes, it's no longer reproducible. that's the problem.

**Comment by SSE4** [comment]
> Anyway, if you already have the docker image and it runs, I see no point on building it again (if the purpose is not to debug the build process) 🤷

it bites even us, as soon as we want to customize anything. (e.g. upgrade cmake version, or any other tool).
to make the situation even worse, it's delayed - it may break many days later than the actual breakage has happened, if you didn't rebuild for a while.

**Comment by jgsogo** [comment]
Yes, and the test suite fails. And, if we really need that version, we can fix and workaround the issue, but if those are versions that we no longer need, maybe it is better to move forward.

It happens to us not only because of Conan, but it has also happened because of the Git version a couple of weeks ago... basically it can bite us with every single binary that runs inside the image. Locking the version of `Markupsafe` **only for a range of Conan versions** adds logic and complexity and addresses the problem just for one out of a thousand libraries that are inside the docker.
