### ISSUE TITLE
Move important legacy images to Jenkins

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#380]
Not good, Azure just dropped our support. I sent a new free-tier request but it takes 2-3 days. 

https://dev.azure.com/conanio/conan-docker-tools/_build/results?buildId=1058&view=results

So far, some people said to use local machine as slave:

https://stackoverflow.com/questions/68405027/how-to-resolve-no-hosted-parallelism-has-been-purchased-or-granted-in-free-tie

Possible solution to avoid it in the future is building all images on Jenkins

### Environment Details
* Conan Docker Tools image: **conanio/gcc7:1.13.1**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Python version (If you are building some image): **python 3.7.0**

**Comment by Croydon** [comment]
That is somewhat weird. Most information is 6+ months old and talks only about limitations for **new** projects. 

Only the infobox at the top of https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs sounds like ALL projects got removed from the free tier, but that would be a pretty radical step and their inbox would get flooded with requests 



> Note
We have temporarily disabled the free grant of parallel jobs for public projects and for certain private projects in new organizations. However, you can request this grant by submitting [a request](https://aka.ms/azpipelines-parallelism-request). Existing organizations and projects are not affected. Please note that it takes us 2-3 business days to respond to your free tier requests.

**Comment by uilianries** [comment]
I sent the form, let's see the answer ... There is no free lunch my friend, someone has to pay the bill at the end.

I'm happy with Azure, it's fast. Moving to jenkins is not a problem for us, only one step more to be implemented.
