### ISSUE TITLE
Debug format issue with modern images?

### ISSUE THREAD

**Issue by db4** [conan-io/conan-docker-tools#391]
### Environment Details
* Conan Docker Tools image: **conanio/gcc7-ubuntu16.04**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**

I'm trying to packages some internal libraries using `conanio/gcc7-ubuntu16.04` image and use them in a consumer build on Ubuntu 18.04 (gcc 7.5.0). A strange thing happens when linking a .so consumer library:

```
[build] /usr/bin/ld: /home/user/.conan/data/xxx/2.9.2/rt/testing/package/aa3afc8eeaab8762bed41415720df294c1bf5e8c/lib/libxxx.a(xxx.cpp.o): unable to initialize decompress status for section .debug_info
[build] /usr/bin/ld: /home/user/.conan/data/xxx/2.9.2/rt/testing/package/aa3afc8eeaab8762bed41415720df294c1bf5e8c/lib/libxxx.a(xxx.cpp.o): unable to initialize decompress status for section .debug_info
[build] /home/user/.conan/data/xxx/2.9.2/rt/testing/package/aa3afc8eeaab8762bed41415720df294c1bf5e8c/lib/libxxx.a: error adding symbols: File format not recognized
[build] collect2: error: ld returned 1 exit status
```

Looks like gcc debugging info formats in conanio/gcc7-ubuntu16.04 and Ubuntu 18.04 are incompatible. Do you have any idea how to work around this?

**Comment by db4** [comment]
More info on the issue.

The problem is in binutils. The latest `conanio/gcc7-ubuntu16.04` contains binutils 2.37 while Ubuntu 18.04 contains 2.30. The latter has a bug that has been fixed in 2.32 (https://sourceware.org/bugzilla/show_bug.cgi?id=23919). The bug effectively prohibits linking .o files created with binutils 2.37.

I was able to work around the issue using `conanio/gcc7-ubuntu16.04:1.42.2` (the most recent version before binutils 2.37 was introduced). As far as I understand it, binutils 2.37 is needed for GCC11. Maybe we should use binutils from Xenial distribution for older compilers?

**Comment by uilianries** [comment]
@db4 The idea is consuming everything from Conan packages, including binutils. The problem is compatibility. We can't change a package version, or a library without checking any possible problem. There are official package already distributed using those images, so any incorrect update could break official packages. Thank you for checking and clarifying the situation.

**Comment by db4** [comment]
@uilianries I must be missing something. This `conanio/gcc7` is not a "modern" image based on Ubuntu Xenial, right? (it contains binutils 2.29). And those `conanio/*-ubuntu16.04` images are not used at CCI yet?

**Comment by uilianries** [comment]
> This conanio/gcc7 is not a "modern" image based on Ubuntu Xenial, right?

Yes. It uses Ubuntu Artful (17.10). The recipe can checked here: https://github.com/conan-io/conan-docker-tools/blob/master/legacy/gcc_7/Dockerfile#L1

> And those conanio/*-ubuntu16.04 images are not used at CCI yet?

They are. GCC 10 and 11, also Clang 12 and 13 are from "modern". Also, any new compiler version will com from there. As we can not simply rebuild all official packages due their volume, we preferred to migrate to modern according to new compiler versions. At some point, older compilers will be deprecated.

**Comment by db4** [comment]
I see. So `gcc{5|6|7|8|9}-ubuntu16.04` are NOT actually used to build packages at CCI? Then can we fix them to be compatible with older Ubuntu distributions? (I would use the oldest possible binutils). If not - well, I'll close the issue and modify those images locally.

**Comment by uilianries** [comment]
They are. it's documented here: https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md You can follow this file, we update when we remove or add a new compiler version.

**Comment by uilianries** [comment]
To understand these docker images and versions ...

We started all docker images with Ubuntu, due its popularity and it's always between top used distros, according DistroWatch. However, it updates their version each 6 months and not all versions are LTS. Therefore, new compilers are released during the time and we need to wait to the next release, to be able to install from official apt repository, or find some external repository. It created a mess between compatibility, different glibc version for instance. So we decided to start new images based on ubuntu 16.04 LTS, which is in the middle in terms of age, and we will build all compilers from source, so can guarantee the compatibility between all images and their packages.

**Comment by db4** [comment]
@uilianries
Just to clarify the situation: should the current CCI binaries be compatible with "modern" gcc images? E.g. if you do
```
conan install poco/1.11.1@ ---build poco
```
in `conanio/gcc7-ubuntu16.04`, it will fail with
```
xmlparse.c:(.text+0x2331): undefined reference to `getrandom'
```
That's because CCI  expat/2.4.1 binary is built with more recent glibc 2.26 (containing `getrandom`) than glibc 2.23 in `conanio/gcc7-ubuntu16.04`. Is this considered a bug that is worth fixing?

**Comment by uilianries** [comment]
>  Just to clarify the situation: should the current CCI binaries be compatible with "modern" gcc images? E.g. if you do

No. They use different glibc version, therefore, all packages are incompatible.

**Comment by db4** [comment]
> No. They use different glibc version, therefore, all packages are incompatible.

I thought the purpose of "modern" images was to build all recent packages in CCI against old enough Glibc (2.23 from Xenial) to be compatible with most modern distros. Probably, I misunderstand something.

**Comment by uilianries** [comment]
That's not the propose, it's impossible to build all packages again, due the big resource needed, it would consume some pentabytes and many weeks to build, meanwhile, we would receive new PR to updates packages. Also, we can't break users due new Docker images.

Read the blog post https://blog.conan.io/2021/08/09/Modern-docker-images.html to understand better.
