### ISSUE TITLE
conanio/gcc11-armv7hf: gcc 11 Page not found on Docker hub

### ISSUE THREAD

**Issue by wiccy46** [conan-io/conan-docker-tools#399]
### Description of Problem, Request, or Question

According to the Readerme table, gcc11-armv7hf is supported but the link returns 404 on Docker Hub. 

### Environment Details
* Conan Docker Tools image: **conanio/gcc11-armv7hf**
* Operating System: **Linux**

**Comment by uilianries** [comment]
Sorry,

We no longer support ARM docker images, because they are not used on Conan Center and are hard to maintain.

The README file is outdated, it should be fixed.

Feel free to open a PR supporting GCC11 ARM if you want.

**Comment by wiccy46** [comment]
Thanks for the info. I think we will try to make our own image based on the legacy templates for now.
