### ISSUE TITLE
[regression] After pulling again `conanio/gcc11-ubuntu16.04:1.46.2`, build fails for `imake`

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-docker-tools#405]
### Description of Problem, Request, or Question

`imake/1.0.8` has stopped to build after pulling latest version of docker image `conanio/gcc11-ubuntu16.04:1.46.2`

### Environment Details
* Conan Docker Tools image: **conanio/gcc11-ubuntu16.04:1.46.2**

### Steps to reproduce (Include if Applicable)

```
docker pull conanio/gcc11-ubuntu16.04:1.46.2
docker run -it conanio/gcc11-ubuntu16.04:1.46.2
conan install imake/1.0.8@ --build=imake --profile:host=default --profile:build=default
```

### Build logs (Include if Available)
```

checking if gcc supports -pedantic... yes
checking if gcc supports -Werror... yes
checking if gcc supports -Werror=attributes... yes
checking whether make supports nested variables... (cached) yes
checking how to run the C preprocessor... gcc -E
checking for cpp... /usr/local/bin/cpp
checking if /usr/local/bin/cpp requires -undef... cpp: fatal error: no input files
compilation terminated.
cpp: fatal error: no input files
compilation terminated.
cpp: fatal error: no input files
compilation terminated.
configure: error: /usr/local/bin/cpp defines unix with or without -undef.  I don't know what to do.

```

**Comment by jgsogo** [comment]
https://github.com/conan-io/conan-docker-tools/blob/6e93c960bb8149f6f3fce652f80df04d57404668/modern/gcc/Dockerfile#L64

I think the error is related to that line. I think `cpp` shouldn´t link to `g++` but to actual cpp (which is C, not C++)

**Comment by uilianries** [comment]
> which is C, not C++

Unbelievable! Good catch @jgsogo !

**Comment by jgsogo** [comment]
Is this C preprocessor available in the GCC build from the `builder` image?

**Comment by uilianries** [comment]
> Is this C preprocessor available in the GCC build from the `builder` image?

I believe so, because we don't exclude anything.
