### ISSUE TITLE
add clang v11-14

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-docker-tools#448]
### Description of Problem, Request, or Question

Please, add new clang versions 11, 12, 13 and 14

**Comment by uilianries** [comment]
They are available already:

https://hub.docker.com/r/conanio/clang14-ubuntu16.04
https://hub.docker.com/r/conanio/clang13-ubuntu16.04
https://hub.docker.com/r/conanio/clang12-ubuntu16.04
https://hub.docker.com/r/conanio/clang11-ubuntu16.04

The Dockerfile can be read here: https://github.com/conan-io/conan-docker-tools/blob/master/modern/clang/Dockerfile

**Comment by AndreyMlashkin** [comment]
Thanks!
