### ISSUE TITLE
Docker image gcc11:1.51.0 contains conan version 1.49.0

### ISSUE THREAD

**Issue by vkhristenko** [conan-io/conan-docker-tools#454]
### Description of Problem, Request, or Question

Docker image `gcc11:1.51.0` contains conan of version `1.49.0`... I would guess that is a bug...

### Environment Details
* Conan Docker Tools image: **conanio/gcc11:1.51.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 20.04**

### Steps to reproduce (Include if Applicable)
```
docker run -it conanio/gcc11:1.51.0 /bin/bash
Unable to find image 'conanio/gcc11:1.51.0' locally
1.51.0: Pulling from conanio/gcc11
Digest: sha256:c1710fa49970a6df517c88eea4faaef3fa6cfd1b8a6616fce657ecb7ba33e7d1
Status: Downloaded newer image for conanio/gcc11:1.51.0
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

conan@9295aa69b791:~$ conan --version
Conan version 1.49.0
```

### Build logs (Include if Available)
see above

**Comment by uilianries** [comment]
@vkhristenko It's a bug, indeed, but I strongly recommend you using `conanio/gcc11-ubuntu16.04:1.51.0` instead. Please, read more: https://github.com/conan-io/conan-docker-tools/tree/master/modern
