### ISSUE TITLE
Provide android cross-compile docker example

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-docker-tools#458]
### Description of Problem, Request, or Question
Please, provide a modern way of cross compiling from Linux to Android.
The best example would be a valid docker image.

For now, there are only deprecated images for cross-compilation.

**Comment by uilianries** [comment]
Done in the official documentation: https://docs.conan.io/en/latest/integrations/cross_platform/android.html#using-docker-images

**Comment by AndreyMlashkin** [comment]
awesom

**Comment by uilianries** [comment]
@AndreyMlashkin Tell if it's not clear enough, there is always margin for improvements in the documentation.
