### ISSUE TITLE
Wrong option spelling when building gcc?

### ISSUE THREAD

**Issue by maksim-petukhov** [conan-io/conan-docker-tools#460]
### Description of Problem, Request, or Question

When building GCC `disable-nsl` option is used:
https://github.com/conan-io/conan-docker-tools/blob/4d3730dde48a819e531125a54d99f67f91663ecc/modern/gcc/Dockerfile#L39

I don't see it there https://gcc.gnu.org/install/configure.html. Shouldn't it be `disable-nls` instead?

**Comment by uilianries** [comment]
@maksim-petukhov Yes, it makes total sense. The only reference related to nsl is the library, but when we want to disable some library, we should use `without` instead. I gonna open a PR fixing that typo. Thank you for spotting it.
