### ISSUE TITLE
typo in dockerfile   

### ISSUE THREAD

**Issue by tankeco** [conan-io/conan-docker-tools#469]
### Description of Problem, Request, or Question

https://github.com/conan-io/conan-docker-tools/blob/master/legacy/android-clang_14-armv8/Dockerfile#L10

Is it a typo? dosetect -> detect

same in android-clang_14-armv7, android-clang_14-x86 and android-clang_14

**Comment by uilianries** [comment]
Yes, it's a typo. A new PR (#470) has been created to fix it.
