### ISSUE TITLE
Provide community images support

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#475]
### Description of Problem, Request, or Question

So far, CDT has been receiving new requests related to ARM and Android support but they are not used by Conan Center, which makes not possible to be maintained.

Also, legacy folder contains images which are still used by the community, like those focused on ARM. (e.g conanio/gcc10-armv7)

As CDT marked them as deprecated on the README file, no new updates are being accepted, and users are being affected, even when they want to provide a solution. The CDT is basically rejecting new updates.

As a possible solution, a new folder to the community could be created, where legacy images related to ARM and Android could be moved, or even modern images could be adapted. The difference is: not marking them as deprecated, but always updated and maintained by the community. However, those images should not be used by Conan Center CI and features request or customization should be targeted to community folder only.

Possibly, a new image name can be created and PR can be executed on GH actions, so it would not affect the internal CDT CI.

**Comment by Croydon** [comment]
I like the idea. The docker image names could contain something like `community` as part of their name, so there can never be any kind of name collision 🤔
