### ISSUE TITLE
Publish docker images on Artifactory

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#499]
### Description of Problem, Request, or Question

As Hub Docker is [sunsetting](https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf) their support to free organizations, we decided to move to Artifactory as main repository.

Some inclinations which made this decision:
- The only free account available will Personal, which is limited to a single user and 200 image pulls every 6h (it may break users)
- Paid team plan does not allow anonymous users, so the community could not download our images
- A second option would be Github Container Registry, but any user must be logged in to download an image, which is not good
- Using Artifactory we will need to do some internal migration and people will need to registry as a remote before download their images, but will be free and accept anonymous users
-

**Comment by Croydon** [comment]
Some notes on that:
  * if you have the resources please migrate all images and all tags for a complete migration of all data
  * once migration is done, you can delete the organization and re-create a new free user account with the organization name, this prevents someone else from doing it and publishing harmful containers under the old address

**Comment by RubenRBS** [comment]
Thanks for the info @Croydon, really appreciated :)

**Comment by uilianries** [comment]
@Croydon Nice observation!!! Danke!

**Comment by Croydon** [comment]
Docker reversed their sun-setting of Free Teams. So they will continue to exist. You don't have to migrate any longer

**Comment by uilianries** [comment]
Closing it as hub.docker.com is still running.
