### ISSUE TITLE
Use python 3.6 for conan docker images

### ISSUE THREAD

**Issue by db4** [conan-io/conan-docker-tools#53]
Conan docker images use python 2.7 as a default interpreter. Python 2 is going to be [deprecated soon](https://docs.conan.io/en/latest/installation.html#python2) by conan, maybe it's time to switch to 3.6?

**Comment by uilianries** [comment]
I agree!

**Comment by uilianries** [comment]
I'll do it :muscle:

**Comment by lasote** [comment]
Released
