### ISSUE TITLE
gcc11 conan 2.0 image

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan-docker-tools#538]
I would like to run a gcc11 container with conan 2.0 corresponding to what the conan-center-index build server uses to build packages.

I cannot seem to find such an image anywhere.

The conanio/gcc11-ubuntu18.04 image seems to have conan 1.54 installed:

```
podman run conanio/gcc11-ubuntu18.04 bash -c "conan -v"
Conan version 1.54.0
```

I also cannot find instructions on how to create such an image corresponding to the image used by conan-center-index build servers.

Can anybody point me in the right direction?

Regards
Klaus

**Comment by uilianries** [comment]
@klausholstjacobsen Not for now, because those images in Conan Docker tools are only focused for Conan Center Index and we are not using 18.04 yet. 

You can update the conan client version and commit a new docker image locally:

```
docker run --name=conan-209 --rm -ti conanio/gcc11-ubuntu18.04
pip install conan==2.0.9
```

Then in another console tab:

```
docker commit conan-209 conanio/gcc11-ubuntu18.04:2.0.9
```

**Comment by klausholstjacobsen** [comment]
LOVE IT!
