### ISSUE TITLE
clang 7 support

### ISSUE THREAD

**Issue by 3galki** [conan-io/conan-docker-tools#54]
clang 7 already in release state. Have you plans to add it to your docker tools?

**Comment by lasote** [comment]
Of course.  Any help is very welcomed.

**Comment by intelligide** [comment]
I'm creating the Dockerfiles [here](https://github.com/intelligide/conan-docker-tools/tree/clang-7). They are based on Ubuntu cosmic, that's going to be released next month ([Planned for 
october 18th](https://wiki.ubuntu.com/CosmicCuttlefish/ReleaseSchedule)). It's pretty stable but there is small troubles. So I will PR after Cosmic Final Release.

**Comment by Croydon** [comment]
From the release notes
https://releases.llvm.org/7.0.0/tools/clang/docs/ReleaseNotes.html

> Clang binary and libraries have been renamed from 7.0 to 7. For example, the clang binary will be called clang-7 instead of clang-7.0.

So we should name the directories, strings etc. just `7` instead of `7.0` as well.

**Comment by Croydon** [comment]
Also we might want to start to install Python 3.6 in new containers?

**Comment by lasote** [comment]
Yes: https://github.com/conan-io/conan-docker-tools/issues/53
