### ISSUE TITLE
Issues building Conan 2 GCC images with Docker Compose

### ISSUE THREAD

**Issue by rob-baily** [conan-io/conan-docker-tools#559]
### Description of Problem, Request, or Question

I have been trying to use the modern path in the repo to build Conan 2 images and have run into a couple problems.

- It seems the base Dockerfile is only set up for Conan 1.0.  The conan install command in there only works in version 1 and not version 2.    It actually seems that it is not needed for Conan 2.0.
- Using the Docker Compose commands results for GCC images in an error in the builder step because there is no gcc-builder target available.

### Environment Details
* Conan Docker Tools image: **N/A**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 20.04.06**  Building for ubuntu18.04
* Python version (If you are building some image): **N/A**

### Steps to reproduce (Include if Applicable)

Run the commands as provided in the documentation for modern: https://github.com/conan-io/conan-docker-tools/tree/master/modern

- _docker-compose build base_ ->This shows the first error for the conan install command.
- _docker-compose build gcc12-builder_ -> This shows the error for the target gcc-builder.

### Build logs (Include if Available)

Will add later. I have resolved these locally so don't have the logs handy but I will go back and get them.

**Comment by uilianries** [comment]
@rob-baily Thank you for reporting, indeed the docker-compose is not used to build official images, we have been using docker commands directly with Jenkins. In case you have some idea about fix it, please, feel free to send a pull request.

**Comment by rob-baily** [comment]
@uilianries Please review my PR and see what you think.  I am not actually clear on how the Conan 2 images are created today as it did not work for me to just update the CONAN_VERSION env.
