### ISSUE TITLE
Include foreign architectures in sources.list file

### ISSUE THREAD

**Issue by ehargitt** [conan-io/conan-docker-tools#57]
Hello,

I have been unable to resolve non-Conan dependencies using the package manager with the Ubuntu images. This is due to these images' `/etc/apt/sources.list` files missing the entries for their respective build architectures. Each entry varies according to distro release, build architecture, and end-of-life status. This is a lot of logic to put in a Conan recipe, and the effort will be multiplied by each person who needs to solve this problem.

I propose that each Ubuntu Docker image meant for cross-compiling contains the entries for its build architecture. I also propose that all the needed `dpkg` commands are issued.

The motivation behind this is that when creating a new Conan recipe for an existing library, it is prudent to temporarily resolve library dependencies with the package manager until a recipe can be created for the dependency.

Let me know if this is a good/bad idea. I would be willing to do the work and submit a PR.

**Comment by lasote** [comment]
In principle, it sounds good!

**Comment by ehargitt** [comment]
@lasote Please see #62  to see if this works for you.

**Comment by uilianries** [comment]
Hey @ehargitt I think we could close this one. The PR #101 implemented this one, didn't it?

**Comment by ehargitt** [comment]
Yep looks like it. Closing.

**Comment by uilianries** [comment]
Thanks!
