### ISSUE TITLE
Impossible to build Qt on recent docker images

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-docker-tools#64]
When building Qt on travis on gcc6/gcc7/gcc8/clang39/clang40/clang50/clang60 x86 and x64 docker images, we systematically have an early fail, which seems to be linked to the following issue https://bugreports.qt.io/browse/QTBUG-64490
I'm not very familiar with containers internals, but it happens when combining [kernel >= 4.12](http://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.10.0#n502) and [docker < 18.04](https://github.com/moby/moby/pull/36417#issuecomment-370782801)
I identified the following solutions
1. upgrade gcc and clang images to cosmic, which has docker 18.06
2. use use `--security-opt seccomp=/path/to/seccomp/profile.json` to specify a different profile when running docker, where profile.json whitelists statx

I did not have a chance to test these solutions . Is there a simple way to reproduce a travis build locally ?

**Comment by ericLemanissier** [comment]
Sorry, I made a confusion between the docker host and the docker container. The failure I face depends on host only, so there is nothing to change in docker images. It also means that the fix I needed is trivial: removing `dist: xenial` from travis.yml so that it switches to trusty

**Comment by uilianries** [comment]
@ericLemanissier  Thanks for reporting this!

We updated our conan template to run xenial by default. If you found a problem, we should revert to trusty immediately.

**Comment by ericLemanissier** [comment]
I noticed the problem after running the tool to update the recipe to the new template format, but I think the problem happens mainly when building Qt

**Comment by uilianries** [comment]
Anyway, xenial is beta yet, we could wait until get it stabilized.

**Comment by Croydon** [comment]
> upgrade gcc and clang images to cosmic, which has docker 18.06

I'm confused about this. Is the Qt build running containers within containers? Or did you mean updating the build host to Cosmic?

**Comment by ericLemanissier** [comment]
Don't be confused, there is no container within container. It is me who made the confusion between the host and the container when I reported the issue.

**Comment by Croydon** [comment]
@ericLemanissier Would you be willing to open an issue in https://github.com/travis-ci/travis-ci/issues to request an update of Docker, including a short explanation why we need it?

**Comment by ericLemanissier** [comment]
done: https://github.com/travis-ci/travis-ci/issues/10296
