### ISSUE TITLE
mingw based docker image

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-docker-tools#80]
Once we have a visual studio image working well on travis and azure pipelines, if someone has time, it would be good to have a docker image with mingw installed.  i know there is already a conan-mingw_installer package, however a docker image has the distinction of being usable by people who aren't using conan directly. 

Dockcross project already has some mingw images that probably show the way pretty well: 

https://github.com/dockcross/dockcross

Apparently though, this only has 64 bit MinGW.  a 32 bit MinGW image would also be required by some.

**Comment by SSE4** [comment]
@solvingj this has been implemented at https://github.com/conan-io/conan-docker-tools/pull/102
