### ISSUE TITLE
autoconf-archive might be useful

### ISSUE THREAD

**Issue by mbeach** [conan-io/conan-docker-tools#81]
Hi, it might be useful to add autoconf-archive to the docker images, in order to handle configure.ac files that utilise AX_ macros from autoconf-archive. I've just struck this while packaging libgpiod. I'm happy to put together a PR if this would be of interest.

**Comment by uilianries** [comment]
as we use docker images for projects on Linux, your request sounds reasonable :+1:

go ahead
