### ISSUE TITLE
Docker image for ancient glibc version

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-docker-tools#82]
Related with https://github.com/conan-io/conan/issues/3963

**Comment by Croydon** [comment]
If we can use a CentOS version (or similar) which is still supported this would be best in my opinion. I feel uncomfortable that we are using many end of life Ubuntu versions for the Docker images right now.

**Comment by uilianries** [comment]
I agree with @Croydon On my last adventure with Docker images, I spent 1 full day trying to fix ubuntu 12.04 to run python 3

I'll spend some hours creating a image based on CentOS 7 to check the compatibility  with our old ubuntu (gcc-4.6 gcc-4.8) images.

**Comment by lasote** [comment]
Just to clarify, I don't want to change the current gcc images, at least not now. Just to create a new one for the glibc issue that can be based on centos if you want.

**Comment by uilianries** [comment]
okay, I have a Docker recipe for Centos6 (glibc 2.12) + GCC7 working here, but I don't know which name I should use...

Suggestions:
- conanio/conan_installer
- conanio/gcc7:centos
- conanio/centos:6

I'll open a PR to show the recipe

**Comment by Croydon** [comment]
I would prefer
`conanio/gcc7:centos`
