### ISSUE TITLE
build with CONAN_DOCKER_IMAGE_SKIP_UPDATE=1 fails

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-docker-tools#87]
I tried to build ninja_installer with `CONAN_DOCKER_IMAGE_SKIP_UPDATE=1` as documentation suggests.
currently, there is no point wasting time on conan update, as CDT rebuilt after conan or CPT releases.
unfortunately, it fails with the following error message:
```
/bin/sh: run_create_in_docker: command not found

```
full log at https://travis-ci.com/bincrafters/conan-ninja_installer/jobs/165005420

/cc @uilianries

**Comment by uilianries** [comment]
Confirmed, it's a bug
