### ISSUE TITLE
Update Sudo-enabled Trusty images

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#9]
As Travis blog mentioned [here](https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2), `sudo: required` rule will be update soon.  
Conan docker image for gcc-4.8 uses Trusty image and sudo option.

**Comment by Croydon** [comment]
What is this issue about? From what I can see there aren't changes required in conan-docker-tools to get these updates.

**Comment by uilianries** [comment]
It's true! My fault! The group should be set in travis.yml file, not in docker image.

**Comment by Croydon** [comment]
Again: Not necessary. Everyone will get this new image very soon. Adding the keyword just enables people to test it even earlier.
