### ISSUE TITLE
gcc_7-centos6 - returned a non-zero code: 4294967295

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan-docker-tools#90]
I tried building this example but it fails almost immediately with this error. I'm not sure if this image is built by CI or not.  Can anyone else build and see if they can reproduce?

**Comment by uilianries** [comment]
Hi @solvingj !

Which example do you mean?

**Comment by solvingj** [comment]
gcc_7-centos6

**Comment by uilianries** [comment]
It worked for me: 

    $ GCC_VERSIONS="7" DOCKER_ARCHS="x86_64" DOCKER_DISTRO="centos6" python build.py

Which command did you run?

**Comment by solvingj** [comment]
i just ran `docker build . -t centostest`

**Comment by uilianries** [comment]
okay, I'll try here

**Comment by uilianries** [comment]
It's working here. I've pasted my log [here](https://gist.github.com/uilianries/174304859d4aed242b1908bbcde08898)

My docker version is:

    Docker version 18.03.1-ce, build 9ee9f40

Could you please paste your log?

**Comment by solvingj** [comment]
Thanks, found the problem, it's documented here: 

https://hub.docker.com/_/centos/

Under section "A note about vsyscall". 

Just Centos6 problems :(

**Comment by solvingj** [comment]
no, i think windows and wsl just can't use centos6 base.
