### ISSUE TITLE
Docker image for clang 8

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#97]
Clang 8 is available: https://apt.llvm.org/bionic/dists/llvm-toolchain-bionic-8/

**Comment by Croydon** [comment]
Maybe we should at least wait until it is available via official Ubuntu packages?

**Comment by uilianries** [comment]
An user has requested this support, let's check when the official support will be available.

**Comment by uilianries** [comment]
Ubuntu Disco is not stable enough to support Clang 8

**Comment by uilianries** [comment]
UPDATE: The status is the same :disappointed: 

https://bugs.launchpad.net/ubuntu/+source/llvm-defaults/+bug/1819768
