### ISSUE TITLE
upgrade gcc 4.9 to xenial

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-docker-tools#98]
Is it possible to upgrade gcc 4.9 x86 and x86_64 images to use ubuntu:xenial as base image ?
The problem I have is that I need to have xkbcommon lib >= 0.5.0 to build Qt package, but trusty provides 0.4.1

**Comment by uilianries** [comment]
Hmmm it's hard I would say ...

Our docker image for gcc 4.9 is based on Ubuntu Trusty, the main problem is the glibc version: 2.19-0ubuntu6.14

Xenial provides by default the gcc 5.3 and glib 2.23

I'm not opposite to update if you need, I see the value your job with Qt, but it could break many users, even packages already built and published.

Do you know how complex is build xkbcommon on gcc 4.9 (Ubuntu trusty)? Maybe we could provide such package for you.

**Comment by ericLemanissier** [comment]
xkbcommon is now [packaged](https://github.com/bincrafters/conan-xkbcommon), so I have no more reason to update gcc 4.9 image
